/*
Open Bank Project API v6.0.0

The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API

API version: 6.0.0
Contact: contact@tesobe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obp

import (
	"encoding/json"
)

// checks if the UpdateAtmLocationCategories200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAtmLocationCategories200Response{}

// UpdateAtmLocationCategories200Response struct for UpdateAtmLocationCategories200Response
type UpdateAtmLocationCategories200Response struct {
	AtmId *string `json:"atm_id,omitempty"`
	LocationCategories []string `json:"location_categories,omitempty"`
}

// NewUpdateAtmLocationCategories200Response instantiates a new UpdateAtmLocationCategories200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAtmLocationCategories200Response() *UpdateAtmLocationCategories200Response {
	this := UpdateAtmLocationCategories200Response{}
	return &this
}

// NewUpdateAtmLocationCategories200ResponseWithDefaults instantiates a new UpdateAtmLocationCategories200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAtmLocationCategories200ResponseWithDefaults() *UpdateAtmLocationCategories200Response {
	this := UpdateAtmLocationCategories200Response{}
	return &this
}

// GetAtmId returns the AtmId field value if set, zero value otherwise.
func (o *UpdateAtmLocationCategories200Response) GetAtmId() string {
	if o == nil || IsNil(o.AtmId) {
		var ret string
		return ret
	}
	return *o.AtmId
}

// GetAtmIdOk returns a tuple with the AtmId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAtmLocationCategories200Response) GetAtmIdOk() (*string, bool) {
	if o == nil || IsNil(o.AtmId) {
		return nil, false
	}
	return o.AtmId, true
}

// HasAtmId returns a boolean if a field has been set.
func (o *UpdateAtmLocationCategories200Response) HasAtmId() bool {
	if o != nil && !IsNil(o.AtmId) {
		return true
	}

	return false
}

// SetAtmId gets a reference to the given string and assigns it to the AtmId field.
func (o *UpdateAtmLocationCategories200Response) SetAtmId(v string) {
	o.AtmId = &v
}

// GetLocationCategories returns the LocationCategories field value if set, zero value otherwise.
func (o *UpdateAtmLocationCategories200Response) GetLocationCategories() []string {
	if o == nil || IsNil(o.LocationCategories) {
		var ret []string
		return ret
	}
	return o.LocationCategories
}

// GetLocationCategoriesOk returns a tuple with the LocationCategories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAtmLocationCategories200Response) GetLocationCategoriesOk() ([]string, bool) {
	if o == nil || IsNil(o.LocationCategories) {
		return nil, false
	}
	return o.LocationCategories, true
}

// HasLocationCategories returns a boolean if a field has been set.
func (o *UpdateAtmLocationCategories200Response) HasLocationCategories() bool {
	if o != nil && !IsNil(o.LocationCategories) {
		return true
	}

	return false
}

// SetLocationCategories gets a reference to the given []string and assigns it to the LocationCategories field.
func (o *UpdateAtmLocationCategories200Response) SetLocationCategories(v []string) {
	o.LocationCategories = v
}

func (o UpdateAtmLocationCategories200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAtmLocationCategories200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AtmId) {
		toSerialize["atm_id"] = o.AtmId
	}
	if !IsNil(o.LocationCategories) {
		toSerialize["location_categories"] = o.LocationCategories
	}
	return toSerialize, nil
}

type NullableUpdateAtmLocationCategories200Response struct {
	value *UpdateAtmLocationCategories200Response
	isSet bool
}

func (v NullableUpdateAtmLocationCategories200Response) Get() *UpdateAtmLocationCategories200Response {
	return v.value
}

func (v *NullableUpdateAtmLocationCategories200Response) Set(val *UpdateAtmLocationCategories200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAtmLocationCategories200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAtmLocationCategories200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAtmLocationCategories200Response(val *UpdateAtmLocationCategories200Response) *NullableUpdateAtmLocationCategories200Response {
	return &NullableUpdateAtmLocationCategories200Response{value: val, isSet: true}
}

func (v NullableUpdateAtmLocationCategories200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAtmLocationCategories200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


