/*
Open Bank Project API v6.0.0

The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API

API version: 6.0.0
Contact: contact@tesobe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obp

import (
	"encoding/json"
)

// checks if the UpdateBankRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateBankRequest{}

// UpdateBankRequest struct for UpdateBankRequest
type UpdateBankRequest struct {
	BankRoutings []GetCheckbookOrders200ResponseAccountAccountRoutingsInner `json:"bank_routings,omitempty"`
	Website *string `json:"website,omitempty"`
	FullName *string `json:"full_name,omitempty"`
	Logo *string `json:"logo,omitempty"`
	Id *string `json:"id,omitempty"`
	BankCode *string `json:"bank_code,omitempty"`
}

// NewUpdateBankRequest instantiates a new UpdateBankRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateBankRequest() *UpdateBankRequest {
	this := UpdateBankRequest{}
	return &this
}

// NewUpdateBankRequestWithDefaults instantiates a new UpdateBankRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateBankRequestWithDefaults() *UpdateBankRequest {
	this := UpdateBankRequest{}
	return &this
}

// GetBankRoutings returns the BankRoutings field value if set, zero value otherwise.
func (o *UpdateBankRequest) GetBankRoutings() []GetCheckbookOrders200ResponseAccountAccountRoutingsInner {
	if o == nil || IsNil(o.BankRoutings) {
		var ret []GetCheckbookOrders200ResponseAccountAccountRoutingsInner
		return ret
	}
	return o.BankRoutings
}

// GetBankRoutingsOk returns a tuple with the BankRoutings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBankRequest) GetBankRoutingsOk() ([]GetCheckbookOrders200ResponseAccountAccountRoutingsInner, bool) {
	if o == nil || IsNil(o.BankRoutings) {
		return nil, false
	}
	return o.BankRoutings, true
}

// HasBankRoutings returns a boolean if a field has been set.
func (o *UpdateBankRequest) HasBankRoutings() bool {
	if o != nil && !IsNil(o.BankRoutings) {
		return true
	}

	return false
}

// SetBankRoutings gets a reference to the given []GetCheckbookOrders200ResponseAccountAccountRoutingsInner and assigns it to the BankRoutings field.
func (o *UpdateBankRequest) SetBankRoutings(v []GetCheckbookOrders200ResponseAccountAccountRoutingsInner) {
	o.BankRoutings = v
}

// GetWebsite returns the Website field value if set, zero value otherwise.
func (o *UpdateBankRequest) GetWebsite() string {
	if o == nil || IsNil(o.Website) {
		var ret string
		return ret
	}
	return *o.Website
}

// GetWebsiteOk returns a tuple with the Website field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBankRequest) GetWebsiteOk() (*string, bool) {
	if o == nil || IsNil(o.Website) {
		return nil, false
	}
	return o.Website, true
}

// HasWebsite returns a boolean if a field has been set.
func (o *UpdateBankRequest) HasWebsite() bool {
	if o != nil && !IsNil(o.Website) {
		return true
	}

	return false
}

// SetWebsite gets a reference to the given string and assigns it to the Website field.
func (o *UpdateBankRequest) SetWebsite(v string) {
	o.Website = &v
}

// GetFullName returns the FullName field value if set, zero value otherwise.
func (o *UpdateBankRequest) GetFullName() string {
	if o == nil || IsNil(o.FullName) {
		var ret string
		return ret
	}
	return *o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBankRequest) GetFullNameOk() (*string, bool) {
	if o == nil || IsNil(o.FullName) {
		return nil, false
	}
	return o.FullName, true
}

// HasFullName returns a boolean if a field has been set.
func (o *UpdateBankRequest) HasFullName() bool {
	if o != nil && !IsNil(o.FullName) {
		return true
	}

	return false
}

// SetFullName gets a reference to the given string and assigns it to the FullName field.
func (o *UpdateBankRequest) SetFullName(v string) {
	o.FullName = &v
}

// GetLogo returns the Logo field value if set, zero value otherwise.
func (o *UpdateBankRequest) GetLogo() string {
	if o == nil || IsNil(o.Logo) {
		var ret string
		return ret
	}
	return *o.Logo
}

// GetLogoOk returns a tuple with the Logo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBankRequest) GetLogoOk() (*string, bool) {
	if o == nil || IsNil(o.Logo) {
		return nil, false
	}
	return o.Logo, true
}

// HasLogo returns a boolean if a field has been set.
func (o *UpdateBankRequest) HasLogo() bool {
	if o != nil && !IsNil(o.Logo) {
		return true
	}

	return false
}

// SetLogo gets a reference to the given string and assigns it to the Logo field.
func (o *UpdateBankRequest) SetLogo(v string) {
	o.Logo = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UpdateBankRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBankRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UpdateBankRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UpdateBankRequest) SetId(v string) {
	o.Id = &v
}

// GetBankCode returns the BankCode field value if set, zero value otherwise.
func (o *UpdateBankRequest) GetBankCode() string {
	if o == nil || IsNil(o.BankCode) {
		var ret string
		return ret
	}
	return *o.BankCode
}

// GetBankCodeOk returns a tuple with the BankCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBankRequest) GetBankCodeOk() (*string, bool) {
	if o == nil || IsNil(o.BankCode) {
		return nil, false
	}
	return o.BankCode, true
}

// HasBankCode returns a boolean if a field has been set.
func (o *UpdateBankRequest) HasBankCode() bool {
	if o != nil && !IsNil(o.BankCode) {
		return true
	}

	return false
}

// SetBankCode gets a reference to the given string and assigns it to the BankCode field.
func (o *UpdateBankRequest) SetBankCode(v string) {
	o.BankCode = &v
}

func (o UpdateBankRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateBankRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BankRoutings) {
		toSerialize["bank_routings"] = o.BankRoutings
	}
	if !IsNil(o.Website) {
		toSerialize["website"] = o.Website
	}
	if !IsNil(o.FullName) {
		toSerialize["full_name"] = o.FullName
	}
	if !IsNil(o.Logo) {
		toSerialize["logo"] = o.Logo
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.BankCode) {
		toSerialize["bank_code"] = o.BankCode
	}
	return toSerialize, nil
}

type NullableUpdateBankRequest struct {
	value *UpdateBankRequest
	isSet bool
}

func (v NullableUpdateBankRequest) Get() *UpdateBankRequest {
	return v.value
}

func (v *NullableUpdateBankRequest) Set(val *UpdateBankRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateBankRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateBankRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateBankRequest(val *UpdateBankRequest) *NullableUpdateBankRequest {
	return &NullableUpdateBankRequest{value: val, isSet: true}
}

func (v NullableUpdateBankRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateBankRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


