/*
Open Bank Project API v6.0.0

The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API

API version: 6.0.0
Contact: contact@tesobe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obp

import (
	"encoding/json"
)

// checks if the CreateProductCollection200ResponseProductCollectionInnerItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProductCollection200ResponseProductCollectionInnerItemsInner{}

// CreateProductCollection200ResponseProductCollectionInnerItemsInner struct for CreateProductCollection200ResponseProductCollectionInnerItemsInner
type CreateProductCollection200ResponseProductCollectionInnerItemsInner struct {
	MemberProductCode *string `json:"member_product_code,omitempty"`
}

// NewCreateProductCollection200ResponseProductCollectionInnerItemsInner instantiates a new CreateProductCollection200ResponseProductCollectionInnerItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProductCollection200ResponseProductCollectionInnerItemsInner() *CreateProductCollection200ResponseProductCollectionInnerItemsInner {
	this := CreateProductCollection200ResponseProductCollectionInnerItemsInner{}
	return &this
}

// NewCreateProductCollection200ResponseProductCollectionInnerItemsInnerWithDefaults instantiates a new CreateProductCollection200ResponseProductCollectionInnerItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProductCollection200ResponseProductCollectionInnerItemsInnerWithDefaults() *CreateProductCollection200ResponseProductCollectionInnerItemsInner {
	this := CreateProductCollection200ResponseProductCollectionInnerItemsInner{}
	return &this
}

// GetMemberProductCode returns the MemberProductCode field value if set, zero value otherwise.
func (o *CreateProductCollection200ResponseProductCollectionInnerItemsInner) GetMemberProductCode() string {
	if o == nil || IsNil(o.MemberProductCode) {
		var ret string
		return ret
	}
	return *o.MemberProductCode
}

// GetMemberProductCodeOk returns a tuple with the MemberProductCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProductCollection200ResponseProductCollectionInnerItemsInner) GetMemberProductCodeOk() (*string, bool) {
	if o == nil || IsNil(o.MemberProductCode) {
		return nil, false
	}
	return o.MemberProductCode, true
}

// HasMemberProductCode returns a boolean if a field has been set.
func (o *CreateProductCollection200ResponseProductCollectionInnerItemsInner) HasMemberProductCode() bool {
	if o != nil && !IsNil(o.MemberProductCode) {
		return true
	}

	return false
}

// SetMemberProductCode gets a reference to the given string and assigns it to the MemberProductCode field.
func (o *CreateProductCollection200ResponseProductCollectionInnerItemsInner) SetMemberProductCode(v string) {
	o.MemberProductCode = &v
}

func (o CreateProductCollection200ResponseProductCollectionInnerItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProductCollection200ResponseProductCollectionInnerItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MemberProductCode) {
		toSerialize["member_product_code"] = o.MemberProductCode
	}
	return toSerialize, nil
}

type NullableCreateProductCollection200ResponseProductCollectionInnerItemsInner struct {
	value *CreateProductCollection200ResponseProductCollectionInnerItemsInner
	isSet bool
}

func (v NullableCreateProductCollection200ResponseProductCollectionInnerItemsInner) Get() *CreateProductCollection200ResponseProductCollectionInnerItemsInner {
	return v.value
}

func (v *NullableCreateProductCollection200ResponseProductCollectionInnerItemsInner) Set(val *CreateProductCollection200ResponseProductCollectionInnerItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProductCollection200ResponseProductCollectionInnerItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProductCollection200ResponseProductCollectionInnerItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProductCollection200ResponseProductCollectionInnerItemsInner(val *CreateProductCollection200ResponseProductCollectionInnerItemsInner) *NullableCreateProductCollection200ResponseProductCollectionInnerItemsInner {
	return &NullableCreateProductCollection200ResponseProductCollectionInnerItemsInner{value: val, isSet: true}
}

func (v NullableCreateProductCollection200ResponseProductCollectionInnerItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProductCollection200ResponseProductCollectionInnerItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


