/*
Open Bank Project API v6.0.0

The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API

API version: 6.0.0
Contact: contact@tesobe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obp

import (
	"encoding/json"
)

// checks if the CreateTransactionRequestCardRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTransactionRequestCardRequest{}

// CreateTransactionRequestCardRequest struct for CreateTransactionRequestCardRequest
type CreateTransactionRequestCardRequest struct {
	Description *string `json:"description,omitempty"`
	Value *GetMyCustomersAtBank200ResponseCustomersInnerCreditLimit `json:"value,omitempty"`
	Card *CreateTransactionRequestCardRequestCard `json:"card,omitempty"`
	To *CreateTransactionRequestCounterpartyRequestTo `json:"to,omitempty"`
}

// NewCreateTransactionRequestCardRequest instantiates a new CreateTransactionRequestCardRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTransactionRequestCardRequest() *CreateTransactionRequestCardRequest {
	this := CreateTransactionRequestCardRequest{}
	return &this
}

// NewCreateTransactionRequestCardRequestWithDefaults instantiates a new CreateTransactionRequestCardRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTransactionRequestCardRequestWithDefaults() *CreateTransactionRequestCardRequest {
	this := CreateTransactionRequestCardRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateTransactionRequestCardRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTransactionRequestCardRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateTransactionRequestCardRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateTransactionRequestCardRequest) SetDescription(v string) {
	o.Description = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CreateTransactionRequestCardRequest) GetValue() GetMyCustomersAtBank200ResponseCustomersInnerCreditLimit {
	if o == nil || IsNil(o.Value) {
		var ret GetMyCustomersAtBank200ResponseCustomersInnerCreditLimit
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTransactionRequestCardRequest) GetValueOk() (*GetMyCustomersAtBank200ResponseCustomersInnerCreditLimit, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CreateTransactionRequestCardRequest) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given GetMyCustomersAtBank200ResponseCustomersInnerCreditLimit and assigns it to the Value field.
func (o *CreateTransactionRequestCardRequest) SetValue(v GetMyCustomersAtBank200ResponseCustomersInnerCreditLimit) {
	o.Value = &v
}

// GetCard returns the Card field value if set, zero value otherwise.
func (o *CreateTransactionRequestCardRequest) GetCard() CreateTransactionRequestCardRequestCard {
	if o == nil || IsNil(o.Card) {
		var ret CreateTransactionRequestCardRequestCard
		return ret
	}
	return *o.Card
}

// GetCardOk returns a tuple with the Card field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTransactionRequestCardRequest) GetCardOk() (*CreateTransactionRequestCardRequestCard, bool) {
	if o == nil || IsNil(o.Card) {
		return nil, false
	}
	return o.Card, true
}

// HasCard returns a boolean if a field has been set.
func (o *CreateTransactionRequestCardRequest) HasCard() bool {
	if o != nil && !IsNil(o.Card) {
		return true
	}

	return false
}

// SetCard gets a reference to the given CreateTransactionRequestCardRequestCard and assigns it to the Card field.
func (o *CreateTransactionRequestCardRequest) SetCard(v CreateTransactionRequestCardRequestCard) {
	o.Card = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *CreateTransactionRequestCardRequest) GetTo() CreateTransactionRequestCounterpartyRequestTo {
	if o == nil || IsNil(o.To) {
		var ret CreateTransactionRequestCounterpartyRequestTo
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTransactionRequestCardRequest) GetToOk() (*CreateTransactionRequestCounterpartyRequestTo, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *CreateTransactionRequestCardRequest) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given CreateTransactionRequestCounterpartyRequestTo and assigns it to the To field.
func (o *CreateTransactionRequestCardRequest) SetTo(v CreateTransactionRequestCounterpartyRequestTo) {
	o.To = &v
}

func (o CreateTransactionRequestCardRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTransactionRequestCardRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Card) {
		toSerialize["card"] = o.Card
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	return toSerialize, nil
}

type NullableCreateTransactionRequestCardRequest struct {
	value *CreateTransactionRequestCardRequest
	isSet bool
}

func (v NullableCreateTransactionRequestCardRequest) Get() *CreateTransactionRequestCardRequest {
	return v.value
}

func (v *NullableCreateTransactionRequestCardRequest) Set(val *CreateTransactionRequestCardRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTransactionRequestCardRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTransactionRequestCardRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTransactionRequestCardRequest(val *CreateTransactionRequestCardRequest) *NullableCreateTransactionRequestCardRequest {
	return &NullableCreateTransactionRequestCardRequest{value: val, isSet: true}
}

func (v NullableCreateTransactionRequestCardRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTransactionRequestCardRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


