/*
Open Bank Project API v6.0.0

The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API

API version: 6.0.0
Contact: contact@tesobe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obp

import (
	"encoding/json"
)

// checks if the RefreshUser200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshUser200Response{}

// RefreshUser200Response struct for RefreshUser200Response
type RefreshUser200Response struct {
	DurationTime *string `json:"duration_time,omitempty"`
}

// NewRefreshUser200Response instantiates a new RefreshUser200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshUser200Response() *RefreshUser200Response {
	this := RefreshUser200Response{}
	return &this
}

// NewRefreshUser200ResponseWithDefaults instantiates a new RefreshUser200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshUser200ResponseWithDefaults() *RefreshUser200Response {
	this := RefreshUser200Response{}
	return &this
}

// GetDurationTime returns the DurationTime field value if set, zero value otherwise.
func (o *RefreshUser200Response) GetDurationTime() string {
	if o == nil || IsNil(o.DurationTime) {
		var ret string
		return ret
	}
	return *o.DurationTime
}

// GetDurationTimeOk returns a tuple with the DurationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefreshUser200Response) GetDurationTimeOk() (*string, bool) {
	if o == nil || IsNil(o.DurationTime) {
		return nil, false
	}
	return o.DurationTime, true
}

// HasDurationTime returns a boolean if a field has been set.
func (o *RefreshUser200Response) HasDurationTime() bool {
	if o != nil && !IsNil(o.DurationTime) {
		return true
	}

	return false
}

// SetDurationTime gets a reference to the given string and assigns it to the DurationTime field.
func (o *RefreshUser200Response) SetDurationTime(v string) {
	o.DurationTime = &v
}

func (o RefreshUser200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshUser200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DurationTime) {
		toSerialize["duration_time"] = o.DurationTime
	}
	return toSerialize, nil
}

type NullableRefreshUser200Response struct {
	value *RefreshUser200Response
	isSet bool
}

func (v NullableRefreshUser200Response) Get() *RefreshUser200Response {
	return v.value
}

func (v *NullableRefreshUser200Response) Set(val *RefreshUser200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshUser200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshUser200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshUser200Response(val *RefreshUser200Response) *NullableRefreshUser200Response {
	return &NullableRefreshUser200Response{value: val, isSet: true}
}

func (v NullableRefreshUser200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshUser200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


