/*
Open Bank Project API v6.0.0

The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API

API version: 6.0.0
Contact: contact@tesobe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obp

import (
	"encoding/json"
	"time"
)

// checks if the GetUserLockStatus200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUserLockStatus200Response{}

// GetUserLockStatus200Response struct for GetUserLockStatus200Response
type GetUserLockStatus200Response struct {
	BadAttemptsSinceLastSuccessOrReset *int32 `json:"bad_attempts_since_last_success_or_reset,omitempty"`
	LastFailureDate *time.Time `json:"last_failure_date,omitempty"`
	Username *string `json:"username,omitempty"`
}

// NewGetUserLockStatus200Response instantiates a new GetUserLockStatus200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserLockStatus200Response() *GetUserLockStatus200Response {
	this := GetUserLockStatus200Response{}
	return &this
}

// NewGetUserLockStatus200ResponseWithDefaults instantiates a new GetUserLockStatus200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserLockStatus200ResponseWithDefaults() *GetUserLockStatus200Response {
	this := GetUserLockStatus200Response{}
	return &this
}

// GetBadAttemptsSinceLastSuccessOrReset returns the BadAttemptsSinceLastSuccessOrReset field value if set, zero value otherwise.
func (o *GetUserLockStatus200Response) GetBadAttemptsSinceLastSuccessOrReset() int32 {
	if o == nil || IsNil(o.BadAttemptsSinceLastSuccessOrReset) {
		var ret int32
		return ret
	}
	return *o.BadAttemptsSinceLastSuccessOrReset
}

// GetBadAttemptsSinceLastSuccessOrResetOk returns a tuple with the BadAttemptsSinceLastSuccessOrReset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserLockStatus200Response) GetBadAttemptsSinceLastSuccessOrResetOk() (*int32, bool) {
	if o == nil || IsNil(o.BadAttemptsSinceLastSuccessOrReset) {
		return nil, false
	}
	return o.BadAttemptsSinceLastSuccessOrReset, true
}

// HasBadAttemptsSinceLastSuccessOrReset returns a boolean if a field has been set.
func (o *GetUserLockStatus200Response) HasBadAttemptsSinceLastSuccessOrReset() bool {
	if o != nil && !IsNil(o.BadAttemptsSinceLastSuccessOrReset) {
		return true
	}

	return false
}

// SetBadAttemptsSinceLastSuccessOrReset gets a reference to the given int32 and assigns it to the BadAttemptsSinceLastSuccessOrReset field.
func (o *GetUserLockStatus200Response) SetBadAttemptsSinceLastSuccessOrReset(v int32) {
	o.BadAttemptsSinceLastSuccessOrReset = &v
}

// GetLastFailureDate returns the LastFailureDate field value if set, zero value otherwise.
func (o *GetUserLockStatus200Response) GetLastFailureDate() time.Time {
	if o == nil || IsNil(o.LastFailureDate) {
		var ret time.Time
		return ret
	}
	return *o.LastFailureDate
}

// GetLastFailureDateOk returns a tuple with the LastFailureDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserLockStatus200Response) GetLastFailureDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastFailureDate) {
		return nil, false
	}
	return o.LastFailureDate, true
}

// HasLastFailureDate returns a boolean if a field has been set.
func (o *GetUserLockStatus200Response) HasLastFailureDate() bool {
	if o != nil && !IsNil(o.LastFailureDate) {
		return true
	}

	return false
}

// SetLastFailureDate gets a reference to the given time.Time and assigns it to the LastFailureDate field.
func (o *GetUserLockStatus200Response) SetLastFailureDate(v time.Time) {
	o.LastFailureDate = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *GetUserLockStatus200Response) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserLockStatus200Response) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *GetUserLockStatus200Response) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *GetUserLockStatus200Response) SetUsername(v string) {
	o.Username = &v
}

func (o GetUserLockStatus200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUserLockStatus200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BadAttemptsSinceLastSuccessOrReset) {
		toSerialize["bad_attempts_since_last_success_or_reset"] = o.BadAttemptsSinceLastSuccessOrReset
	}
	if !IsNil(o.LastFailureDate) {
		toSerialize["last_failure_date"] = o.LastFailureDate
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

type NullableGetUserLockStatus200Response struct {
	value *GetUserLockStatus200Response
	isSet bool
}

func (v NullableGetUserLockStatus200Response) Get() *GetUserLockStatus200Response {
	return v.value
}

func (v *NullableGetUserLockStatus200Response) Set(val *GetUserLockStatus200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserLockStatus200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserLockStatus200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserLockStatus200Response(val *GetUserLockStatus200Response) *NullableGetUserLockStatus200Response {
	return &NullableGetUserLockStatus200Response{value: val, isSet: true}
}

func (v NullableGetUserLockStatus200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserLockStatus200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


