/*
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openbankproject.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.openbankproject.ApiClient;
/**
 * CreateVRPConsentRequest200ResponsePayloadToAccountLimit
 */
@JsonPropertyOrder({
  CreateVRPConsentRequest200ResponsePayloadToAccountLimit.JSON_PROPERTY_MAX_MONTHLY_AMOUNT,
  CreateVRPConsentRequest200ResponsePayloadToAccountLimit.JSON_PROPERTY_MAX_NUMBER_OF_MONTHLY_TRANSACTIONS,
  CreateVRPConsentRequest200ResponsePayloadToAccountLimit.JSON_PROPERTY_MAX_SINGLE_AMOUNT,
  CreateVRPConsentRequest200ResponsePayloadToAccountLimit.JSON_PROPERTY_CURRENCY,
  CreateVRPConsentRequest200ResponsePayloadToAccountLimit.JSON_PROPERTY_MAX_NUMBER_OF_YEARLY_TRANSACTIONS,
  CreateVRPConsentRequest200ResponsePayloadToAccountLimit.JSON_PROPERTY_MAX_YEARLY_AMOUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-26T21:47:30.402330+07:00[Asia/Bangkok]", comments = "Generator version: 7.20.0")
public class CreateVRPConsentRequest200ResponsePayloadToAccountLimit {
  public static final String JSON_PROPERTY_MAX_MONTHLY_AMOUNT = "max_monthly_amount";
  @javax.annotation.Nullable
  private Integer maxMonthlyAmount;

  public static final String JSON_PROPERTY_MAX_NUMBER_OF_MONTHLY_TRANSACTIONS = "max_number_of_monthly_transactions";
  @javax.annotation.Nullable
  private Integer maxNumberOfMonthlyTransactions;

  public static final String JSON_PROPERTY_MAX_SINGLE_AMOUNT = "max_single_amount";
  @javax.annotation.Nullable
  private Integer maxSingleAmount;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nullable
  private String currency;

  public static final String JSON_PROPERTY_MAX_NUMBER_OF_YEARLY_TRANSACTIONS = "max_number_of_yearly_transactions";
  @javax.annotation.Nullable
  private Integer maxNumberOfYearlyTransactions;

  public static final String JSON_PROPERTY_MAX_YEARLY_AMOUNT = "max_yearly_amount";
  @javax.annotation.Nullable
  private Integer maxYearlyAmount;

  public CreateVRPConsentRequest200ResponsePayloadToAccountLimit() { 
  }

  public CreateVRPConsentRequest200ResponsePayloadToAccountLimit maxMonthlyAmount(@javax.annotation.Nullable Integer maxMonthlyAmount) {
    this.maxMonthlyAmount = maxMonthlyAmount;
    return this;
  }

  /**
   * Get maxMonthlyAmount
   * @return maxMonthlyAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_MONTHLY_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getMaxMonthlyAmount() {
    return maxMonthlyAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_MONTHLY_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxMonthlyAmount(@javax.annotation.Nullable Integer maxMonthlyAmount) {
    this.maxMonthlyAmount = maxMonthlyAmount;
  }


  public CreateVRPConsentRequest200ResponsePayloadToAccountLimit maxNumberOfMonthlyTransactions(@javax.annotation.Nullable Integer maxNumberOfMonthlyTransactions) {
    this.maxNumberOfMonthlyTransactions = maxNumberOfMonthlyTransactions;
    return this;
  }

  /**
   * Get maxNumberOfMonthlyTransactions
   * @return maxNumberOfMonthlyTransactions
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_NUMBER_OF_MONTHLY_TRANSACTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getMaxNumberOfMonthlyTransactions() {
    return maxNumberOfMonthlyTransactions;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_NUMBER_OF_MONTHLY_TRANSACTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxNumberOfMonthlyTransactions(@javax.annotation.Nullable Integer maxNumberOfMonthlyTransactions) {
    this.maxNumberOfMonthlyTransactions = maxNumberOfMonthlyTransactions;
  }


  public CreateVRPConsentRequest200ResponsePayloadToAccountLimit maxSingleAmount(@javax.annotation.Nullable Integer maxSingleAmount) {
    this.maxSingleAmount = maxSingleAmount;
    return this;
  }

  /**
   * Get maxSingleAmount
   * @return maxSingleAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_SINGLE_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getMaxSingleAmount() {
    return maxSingleAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_SINGLE_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxSingleAmount(@javax.annotation.Nullable Integer maxSingleAmount) {
    this.maxSingleAmount = maxSingleAmount;
  }


  public CreateVRPConsentRequest200ResponsePayloadToAccountLimit currency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }


  public CreateVRPConsentRequest200ResponsePayloadToAccountLimit maxNumberOfYearlyTransactions(@javax.annotation.Nullable Integer maxNumberOfYearlyTransactions) {
    this.maxNumberOfYearlyTransactions = maxNumberOfYearlyTransactions;
    return this;
  }

  /**
   * Get maxNumberOfYearlyTransactions
   * @return maxNumberOfYearlyTransactions
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_NUMBER_OF_YEARLY_TRANSACTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getMaxNumberOfYearlyTransactions() {
    return maxNumberOfYearlyTransactions;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_NUMBER_OF_YEARLY_TRANSACTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxNumberOfYearlyTransactions(@javax.annotation.Nullable Integer maxNumberOfYearlyTransactions) {
    this.maxNumberOfYearlyTransactions = maxNumberOfYearlyTransactions;
  }


  public CreateVRPConsentRequest200ResponsePayloadToAccountLimit maxYearlyAmount(@javax.annotation.Nullable Integer maxYearlyAmount) {
    this.maxYearlyAmount = maxYearlyAmount;
    return this;
  }

  /**
   * Get maxYearlyAmount
   * @return maxYearlyAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_YEARLY_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getMaxYearlyAmount() {
    return maxYearlyAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_YEARLY_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxYearlyAmount(@javax.annotation.Nullable Integer maxYearlyAmount) {
    this.maxYearlyAmount = maxYearlyAmount;
  }


  /**
   * Return true if this createVRPConsentRequest_200_response_payload_to_account_limit object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateVRPConsentRequest200ResponsePayloadToAccountLimit createVRPConsentRequest200ResponsePayloadToAccountLimit = (CreateVRPConsentRequest200ResponsePayloadToAccountLimit) o;
    return Objects.equals(this.maxMonthlyAmount, createVRPConsentRequest200ResponsePayloadToAccountLimit.maxMonthlyAmount) &&
        Objects.equals(this.maxNumberOfMonthlyTransactions, createVRPConsentRequest200ResponsePayloadToAccountLimit.maxNumberOfMonthlyTransactions) &&
        Objects.equals(this.maxSingleAmount, createVRPConsentRequest200ResponsePayloadToAccountLimit.maxSingleAmount) &&
        Objects.equals(this.currency, createVRPConsentRequest200ResponsePayloadToAccountLimit.currency) &&
        Objects.equals(this.maxNumberOfYearlyTransactions, createVRPConsentRequest200ResponsePayloadToAccountLimit.maxNumberOfYearlyTransactions) &&
        Objects.equals(this.maxYearlyAmount, createVRPConsentRequest200ResponsePayloadToAccountLimit.maxYearlyAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxMonthlyAmount, maxNumberOfMonthlyTransactions, maxSingleAmount, currency, maxNumberOfYearlyTransactions, maxYearlyAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateVRPConsentRequest200ResponsePayloadToAccountLimit {\n");
    sb.append("    maxMonthlyAmount: ").append(toIndentedString(maxMonthlyAmount)).append("\n");
    sb.append("    maxNumberOfMonthlyTransactions: ").append(toIndentedString(maxNumberOfMonthlyTransactions)).append("\n");
    sb.append("    maxSingleAmount: ").append(toIndentedString(maxSingleAmount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    maxNumberOfYearlyTransactions: ").append(toIndentedString(maxNumberOfYearlyTransactions)).append("\n");
    sb.append("    maxYearlyAmount: ").append(toIndentedString(maxYearlyAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `max_monthly_amount` to the URL query string
    if (getMaxMonthlyAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smax_monthly_amount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMaxMonthlyAmount()))));
    }

    // add `max_number_of_monthly_transactions` to the URL query string
    if (getMaxNumberOfMonthlyTransactions() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smax_number_of_monthly_transactions%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMaxNumberOfMonthlyTransactions()))));
    }

    // add `max_single_amount` to the URL query string
    if (getMaxSingleAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smax_single_amount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMaxSingleAmount()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `max_number_of_yearly_transactions` to the URL query string
    if (getMaxNumberOfYearlyTransactions() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smax_number_of_yearly_transactions%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMaxNumberOfYearlyTransactions()))));
    }

    // add `max_yearly_amount` to the URL query string
    if (getMaxYearlyAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smax_yearly_amount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMaxYearlyAmount()))));
    }

    return joiner.toString();
  }
}

