/*
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openbankproject.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openbankproject.model.GetCustomersForUser200ResponseCustomersInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.openbankproject.ApiClient;
/**
 * GetCustomersForUser200Response
 */
@JsonPropertyOrder({
  GetCustomersForUser200Response.JSON_PROPERTY_CUSTOMERS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-26T22:05:21.988755+07:00[Asia/Bangkok]", comments = "Generator version: 7.20.0")
public class GetCustomersForUser200Response {
  public static final String JSON_PROPERTY_CUSTOMERS = "customers";
  @javax.annotation.Nullable
  private List<GetCustomersForUser200ResponseCustomersInner> customers = new ArrayList<>();

  public GetCustomersForUser200Response() { 
  }

  public GetCustomersForUser200Response customers(@javax.annotation.Nullable List<GetCustomersForUser200ResponseCustomersInner> customers) {
    this.customers = customers;
    return this;
  }

  public GetCustomersForUser200Response addCustomersItem(GetCustomersForUser200ResponseCustomersInner customersItem) {
    if (this.customers == null) {
      this.customers = new ArrayList<>();
    }
    this.customers.add(customersItem);
    return this;
  }

  /**
   * Get customers
   * @return customers
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOMERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<GetCustomersForUser200ResponseCustomersInner> getCustomers() {
    return customers;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOMERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomers(@javax.annotation.Nullable List<GetCustomersForUser200ResponseCustomersInner> customers) {
    this.customers = customers;
  }


  /**
   * Return true if this getCustomersForUser_200_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCustomersForUser200Response getCustomersForUser200Response = (GetCustomersForUser200Response) o;
    return Objects.equals(this.customers, getCustomersForUser200Response.customers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCustomersForUser200Response {\n");
    sb.append("    customers: ").append(toIndentedString(customers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `customers` to the URL query string
    if (getCustomers() != null) {
      for (int i = 0; i < getCustomers().size(); i++) {
        if (getCustomers().get(i) != null) {
          joiner.add(getCustomers().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%scustomers%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

