/*
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openbankproject.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.openbankproject.ApiClient;
/**
 * UpdateSystemLevelEndpointTag200Response
 */
@JsonPropertyOrder({
  UpdateSystemLevelEndpointTag200Response.JSON_PROPERTY_OPERATION_ID,
  UpdateSystemLevelEndpointTag200Response.JSON_PROPERTY_TAG_NAME,
  UpdateSystemLevelEndpointTag200Response.JSON_PROPERTY_BANK_ID,
  UpdateSystemLevelEndpointTag200Response.JSON_PROPERTY_ENDPOINT_TAG_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-26T22:05:21.988755+07:00[Asia/Bangkok]", comments = "Generator version: 7.20.0")
public class UpdateSystemLevelEndpointTag200Response {
  public static final String JSON_PROPERTY_OPERATION_ID = "operation_id";
  @javax.annotation.Nullable
  private String operationId;

  public static final String JSON_PROPERTY_TAG_NAME = "tag_name";
  @javax.annotation.Nullable
  private String tagName;

  public static final String JSON_PROPERTY_BANK_ID = "bank_id";
  @javax.annotation.Nullable
  private String bankId;

  public static final String JSON_PROPERTY_ENDPOINT_TAG_ID = "endpoint_tag_id";
  @javax.annotation.Nullable
  private String endpointTagId;

  public UpdateSystemLevelEndpointTag200Response() { 
  }

  public UpdateSystemLevelEndpointTag200Response operationId(@javax.annotation.Nullable String operationId) {
    this.operationId = operationId;
    return this;
  }

  /**
   * Get operationId
   * @return operationId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPERATION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOperationId() {
    return operationId;
  }


  @JsonProperty(value = JSON_PROPERTY_OPERATION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperationId(@javax.annotation.Nullable String operationId) {
    this.operationId = operationId;
  }


  public UpdateSystemLevelEndpointTag200Response tagName(@javax.annotation.Nullable String tagName) {
    this.tagName = tagName;
    return this;
  }

  /**
   * Get tagName
   * @return tagName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAG_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTagName() {
    return tagName;
  }


  @JsonProperty(value = JSON_PROPERTY_TAG_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTagName(@javax.annotation.Nullable String tagName) {
    this.tagName = tagName;
  }


  public UpdateSystemLevelEndpointTag200Response bankId(@javax.annotation.Nullable String bankId) {
    this.bankId = bankId;
    return this;
  }

  /**
   * Get bankId
   * @return bankId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BANK_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBankId() {
    return bankId;
  }


  @JsonProperty(value = JSON_PROPERTY_BANK_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBankId(@javax.annotation.Nullable String bankId) {
    this.bankId = bankId;
  }


  public UpdateSystemLevelEndpointTag200Response endpointTagId(@javax.annotation.Nullable String endpointTagId) {
    this.endpointTagId = endpointTagId;
    return this;
  }

  /**
   * Get endpointTagId
   * @return endpointTagId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_TAG_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEndpointTagId() {
    return endpointTagId;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINT_TAG_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpointTagId(@javax.annotation.Nullable String endpointTagId) {
    this.endpointTagId = endpointTagId;
  }


  /**
   * Return true if this updateSystemLevelEndpointTag_200_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateSystemLevelEndpointTag200Response updateSystemLevelEndpointTag200Response = (UpdateSystemLevelEndpointTag200Response) o;
    return Objects.equals(this.operationId, updateSystemLevelEndpointTag200Response.operationId) &&
        Objects.equals(this.tagName, updateSystemLevelEndpointTag200Response.tagName) &&
        Objects.equals(this.bankId, updateSystemLevelEndpointTag200Response.bankId) &&
        Objects.equals(this.endpointTagId, updateSystemLevelEndpointTag200Response.endpointTagId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operationId, tagName, bankId, endpointTagId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateSystemLevelEndpointTag200Response {\n");
    sb.append("    operationId: ").append(toIndentedString(operationId)).append("\n");
    sb.append("    tagName: ").append(toIndentedString(tagName)).append("\n");
    sb.append("    bankId: ").append(toIndentedString(bankId)).append("\n");
    sb.append("    endpointTagId: ").append(toIndentedString(endpointTagId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `operation_id` to the URL query string
    if (getOperationId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soperation_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOperationId()))));
    }

    // add `tag_name` to the URL query string
    if (getTagName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stag_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTagName()))));
    }

    // add `bank_id` to the URL query string
    if (getBankId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbank_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBankId()))));
    }

    // add `endpoint_tag_id` to the URL query string
    if (getEndpointTagId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sendpoint_tag_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndpointTagId()))));
    }

    return joiner.toString();
  }
}

