//
// AddAccountRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddAccountRequest: Sendable, Codable, Hashable {

    public var branchId: String?
    public var accountRoutings: [GetCheckbookOrders200ResponseAccountAccountRoutingsInner]?
    public var label: String?
    public var balance: GetMyCustomersAtBank200ResponseCustomersInnerCreditLimit?
    public var userId: String?
    public var productCode: String?

    public init(branchId: String? = nil, accountRoutings: [GetCheckbookOrders200ResponseAccountAccountRoutingsInner]? = nil, label: String? = nil, balance: GetMyCustomersAtBank200ResponseCustomersInnerCreditLimit? = nil, userId: String? = nil, productCode: String? = nil) {
        self.branchId = branchId
        self.accountRoutings = accountRoutings
        self.label = label
        self.balance = balance
        self.userId = userId
        self.productCode = productCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case branchId = "branch_id"
        case accountRoutings = "account_routings"
        case label
        case balance
        case userId = "user_id"
        case productCode = "product_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(branchId, forKey: .branchId)
        try container.encodeIfPresent(accountRoutings, forKey: .accountRoutings)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(balance, forKey: .balance)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(productCode, forKey: .productCode)
    }
}

