//
// AddSystemViewPermissionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddSystemViewPermissionRequest: Sendable, Codable, Hashable {

    public var extraData: [String]?
    public var permissionName: String?

    public init(extraData: [String]? = nil, permissionName: String? = nil) {
        self.extraData = extraData
        self.permissionName = permissionName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case extraData = "extra_data"
        case permissionName = "permission_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(extraData, forKey: .extraData)
        try container.encodeIfPresent(permissionName, forKey: .permissionName)
    }
}

