//
// CleanupOrphanedDynamicEntityRecords200ResponseDeletedOrphanedEntitiesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CleanupOrphanedDynamicEntityRecords200ResponseDeletedOrphanedEntitiesInner: Sendable, Codable, Hashable {

    public var recordCount: Int?
    public var bankId: String?
    public var entityName: String?

    public init(recordCount: Int? = nil, bankId: String? = nil, entityName: String? = nil) {
        self.recordCount = recordCount
        self.bankId = bankId
        self.entityName = entityName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recordCount = "record_count"
        case bankId = "bank_id"
        case entityName = "entity_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(recordCount, forKey: .recordCount)
        try container.encodeIfPresent(bankId, forKey: .bankId)
        try container.encodeIfPresent(entityName, forKey: .entityName)
    }
}

