//
// GetAllEntitlementRequests200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetAllEntitlementRequests200Response: Sendable, Codable, Hashable {

    public var entitlementRequests: [GetAllEntitlementRequests200ResponseEntitlementRequestsInner]?

    public init(entitlementRequests: [GetAllEntitlementRequests200ResponseEntitlementRequestsInner]? = nil) {
        self.entitlementRequests = entitlementRequests
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entitlementRequests = "entitlement_requests"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(entitlementRequests, forKey: .entitlementRequests)
    }
}

