//
// GetApiTags200ResponseAccountsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetApiTags200ResponseAccountsInner: Sendable, Codable, Hashable {

    public var bankId: String?
    public var viewId: String?
    public var accountId: String?

    public init(bankId: String? = nil, viewId: String? = nil, accountId: String? = nil) {
        self.bankId = bankId
        self.viewId = viewId
        self.accountId = accountId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bankId = "bank_id"
        case viewId = "view_id"
        case accountId = "account_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bankId, forKey: .bankId)
        try container.encodeIfPresent(viewId, forKey: .viewId)
        try container.encodeIfPresent(accountId, forKey: .accountId)
    }
}

