//
// GetBranches200ResponseBranchesInnerDriveUpSunday.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetBranches200ResponseBranchesInnerDriveUpSunday: Sendable, Codable, Hashable {

    public var closingTime: String?
    public var openingTime: String?

    public init(closingTime: String? = nil, openingTime: String? = nil) {
        self.closingTime = closingTime
        self.openingTime = openingTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case closingTime = "closing_time"
        case openingTime = "opening_time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(closingTime, forKey: .closingTime)
        try container.encodeIfPresent(openingTime, forKey: .openingTime)
    }
}

