//
// GetCrmEvents200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetCrmEvents200Response: Sendable, Codable, Hashable {

    public var crmEvents: [GetCrmEvents200ResponseCrmEventsInner]?

    public init(crmEvents: [GetCrmEvents200ResponseCrmEventsInner]? = nil) {
        self.crmEvents = crmEvents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case crmEvents = "crm_events"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(crmEvents, forKey: .crmEvents)
    }
}

