//
// GetCacheConfig200ResponseInMemoryStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetCacheConfig200ResponseInMemoryStatus: Sendable, Codable, Hashable {

    public var available: Bool?
    public var currentSize: Int?

    public init(available: Bool? = nil, currentSize: Int? = nil) {
        self.available = available
        self.currentSize = currentSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case available
        case currentSize = "current_size"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(available, forKey: .available)
        try container.encodeIfPresent(currentSize, forKey: .currentSize)
    }
}

