//
// GetImagesForViewOnTransaction200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetImagesForViewOnTransaction200Response: Sendable, Codable, Hashable {

    public var images: [GetTransactionByIdForBankAccount200ResponseMetadataImagesInner]?

    public init(images: [GetTransactionByIdForBankAccount200ResponseMetadataImagesInner]? = nil) {
        self.images = images
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case images
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(images, forKey: .images)
    }
}

