//
// GetMandateProvision200ResponseSignatoryRequirementsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetMandateProvision200ResponseSignatoryRequirementsInner: Sendable, Codable, Hashable {

    public var requiredCount: Int?
    public var panelId: String?

    public init(requiredCount: Int? = nil, panelId: String? = nil) {
        self.requiredCount = requiredCount
        self.panelId = panelId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requiredCount = "required_count"
        case panelId = "panel_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(requiredCount, forKey: .requiredCount)
        try container.encodeIfPresent(panelId, forKey: .panelId)
    }
}

