//
// GetScannedApiVersions200ResponseScannedApiVersionsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetScannedApiVersions200ResponseScannedApiVersionsInner: Sendable, Codable, Hashable {

    public var isActive: Bool?
    public var urlPrefix: String?
    public var apiShortVersion: String?
    public var fullyQualifiedVersion: String?
    public var apiStandard: String?

    public init(isActive: Bool? = nil, urlPrefix: String? = nil, apiShortVersion: String? = nil, fullyQualifiedVersion: String? = nil, apiStandard: String? = nil) {
        self.isActive = isActive
        self.urlPrefix = urlPrefix
        self.apiShortVersion = apiShortVersion
        self.fullyQualifiedVersion = fullyQualifiedVersion
        self.apiStandard = apiStandard
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isActive = "is_active"
        case urlPrefix = "url_prefix"
        case apiShortVersion = "api_short_version"
        case fullyQualifiedVersion = "fully_qualified_version"
        case apiStandard = "api_standard"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encodeIfPresent(urlPrefix, forKey: .urlPrefix)
        try container.encodeIfPresent(apiShortVersion, forKey: .apiShortVersion)
        try container.encodeIfPresent(fullyQualifiedVersion, forKey: .fullyQualifiedVersion)
        try container.encodeIfPresent(apiStandard, forKey: .apiStandard)
    }
}

