//
// UpdateAtmServicesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateAtmServicesRequest: Sendable, Codable, Hashable {

    public var services: [String]?

    public init(services: [String]? = nil) {
        self.services = services
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case services
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(services, forKey: .services)
    }
}

