//
// UpdateCustomerAccountLinkByIdRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateCustomerAccountLinkByIdRequest: Sendable, Codable, Hashable {

    public var relationshipType: String?

    public init(relationshipType: String? = nil) {
        self.relationshipType = relationshipType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case relationshipType = "relationship_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(relationshipType, forKey: .relationshipType)
    }
}

