=begin
#Open Bank Project API v6.0.0

#The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API

The version of the OpenAPI document: 6.0.0
Contact: contact@tesobe.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module OpenBankProject
  class GetConnectorTraces200ResponseConnectorTracesInner < ApiModelBase
    attr_accessor :connector_name

    attr_accessor :duration

    attr_accessor :function_name

    attr_accessor :outbound_message

    attr_accessor :url

    attr_accessor :correlation_id

    attr_accessor :inbound_message

    attr_accessor :user_id

    attr_accessor :bank_id

    attr_accessor :connector_trace_id

    attr_accessor :date

    attr_accessor :http_verb

    attr_accessor :is_successful

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'connector_name' => :'connector_name',
        :'duration' => :'duration',
        :'function_name' => :'function_name',
        :'outbound_message' => :'outbound_message',
        :'url' => :'url',
        :'correlation_id' => :'correlation_id',
        :'inbound_message' => :'inbound_message',
        :'user_id' => :'user_id',
        :'bank_id' => :'bank_id',
        :'connector_trace_id' => :'connector_trace_id',
        :'date' => :'date',
        :'http_verb' => :'http_verb',
        :'is_successful' => :'is_successful'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'connector_name' => :'String',
        :'duration' => :'Integer',
        :'function_name' => :'String',
        :'outbound_message' => :'String',
        :'url' => :'String',
        :'correlation_id' => :'String',
        :'inbound_message' => :'String',
        :'user_id' => :'String',
        :'bank_id' => :'String',
        :'connector_trace_id' => :'Integer',
        :'date' => :'Time',
        :'http_verb' => :'String',
        :'is_successful' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenBankProject::GetConnectorTraces200ResponseConnectorTracesInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenBankProject::GetConnectorTraces200ResponseConnectorTracesInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'connector_name')
        self.connector_name = attributes[:'connector_name']
      end

      if attributes.key?(:'duration')
        self.duration = attributes[:'duration']
      end

      if attributes.key?(:'function_name')
        self.function_name = attributes[:'function_name']
      end

      if attributes.key?(:'outbound_message')
        self.outbound_message = attributes[:'outbound_message']
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.key?(:'correlation_id')
        self.correlation_id = attributes[:'correlation_id']
      end

      if attributes.key?(:'inbound_message')
        self.inbound_message = attributes[:'inbound_message']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'bank_id')
        self.bank_id = attributes[:'bank_id']
      end

      if attributes.key?(:'connector_trace_id')
        self.connector_trace_id = attributes[:'connector_trace_id']
      end

      if attributes.key?(:'date')
        self.date = attributes[:'date']
      end

      if attributes.key?(:'http_verb')
        self.http_verb = attributes[:'http_verb']
      end

      if attributes.key?(:'is_successful')
        self.is_successful = attributes[:'is_successful']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          connector_name == o.connector_name &&
          duration == o.duration &&
          function_name == o.function_name &&
          outbound_message == o.outbound_message &&
          url == o.url &&
          correlation_id == o.correlation_id &&
          inbound_message == o.inbound_message &&
          user_id == o.user_id &&
          bank_id == o.bank_id &&
          connector_trace_id == o.connector_trace_id &&
          date == o.date &&
          http_verb == o.http_verb &&
          is_successful == o.is_successful
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [connector_name, duration, function_name, outbound_message, url, correlation_id, inbound_message, user_id, bank_id, connector_trace_id, date, http_verb, is_successful].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
