<?php
/**
 * BuildDynamicEndpointTemplate200ResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenBankProject
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenBankProject\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BuildDynamicEndpointTemplate200ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description BuildDynamicEndpointTemplate200Response
 * @package     OpenBankProject
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BuildDynamicEndpointTemplate200ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BuildDynamicEndpointTemplate200Response"
     */
    public function testBuildDynamicEndpointTemplate200Response()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
