// <auto-generated>
/*
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenBankProject.Client;

namespace OpenBankProject.Model
{
    /// <summary>
    /// CreateTransactionRequestSimpleRequestTo
    /// </summary>
    public partial class CreateTransactionRequestSimpleRequestTo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateTransactionRequestSimpleRequestTo" /> class.
        /// </summary>
        /// <param name="otherAccountRoutingAddress">otherAccountRoutingAddress</param>
        /// <param name="otherAccountRoutingScheme">otherAccountRoutingScheme</param>
        /// <param name="name">name</param>
        /// <param name="otherAccountSecondaryRoutingAddress">otherAccountSecondaryRoutingAddress</param>
        /// <param name="description">description</param>
        /// <param name="otherBranchRoutingAddress">otherBranchRoutingAddress</param>
        /// <param name="otherBankRoutingScheme">otherBankRoutingScheme</param>
        /// <param name="otherBranchRoutingScheme">otherBranchRoutingScheme</param>
        /// <param name="otherBankRoutingAddress">otherBankRoutingAddress</param>
        /// <param name="otherAccountSecondaryRoutingScheme">otherAccountSecondaryRoutingScheme</param>
        [JsonConstructor]
        public CreateTransactionRequestSimpleRequestTo(Option<string?> otherAccountRoutingAddress = default, Option<string?> otherAccountRoutingScheme = default, Option<string?> name = default, Option<string?> otherAccountSecondaryRoutingAddress = default, Option<string?> description = default, Option<string?> otherBranchRoutingAddress = default, Option<string?> otherBankRoutingScheme = default, Option<string?> otherBranchRoutingScheme = default, Option<string?> otherBankRoutingAddress = default, Option<string?> otherAccountSecondaryRoutingScheme = default)
        {
            OtherAccountRoutingAddressOption = otherAccountRoutingAddress;
            OtherAccountRoutingSchemeOption = otherAccountRoutingScheme;
            NameOption = name;
            OtherAccountSecondaryRoutingAddressOption = otherAccountSecondaryRoutingAddress;
            DescriptionOption = description;
            OtherBranchRoutingAddressOption = otherBranchRoutingAddress;
            OtherBankRoutingSchemeOption = otherBankRoutingScheme;
            OtherBranchRoutingSchemeOption = otherBranchRoutingScheme;
            OtherBankRoutingAddressOption = otherBankRoutingAddress;
            OtherAccountSecondaryRoutingSchemeOption = otherAccountSecondaryRoutingScheme;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of OtherAccountRoutingAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OtherAccountRoutingAddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets OtherAccountRoutingAddress
        /// </summary>
        [JsonPropertyName("other_account_routing_address")]
        public string? OtherAccountRoutingAddress { get { return this.OtherAccountRoutingAddressOption; } set { this.OtherAccountRoutingAddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of OtherAccountRoutingScheme
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OtherAccountRoutingSchemeOption { get; private set; }

        /// <summary>
        /// Gets or Sets OtherAccountRoutingScheme
        /// </summary>
        [JsonPropertyName("other_account_routing_scheme")]
        public string? OtherAccountRoutingScheme { get { return this.OtherAccountRoutingSchemeOption; } set { this.OtherAccountRoutingSchemeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of OtherAccountSecondaryRoutingAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OtherAccountSecondaryRoutingAddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets OtherAccountSecondaryRoutingAddress
        /// </summary>
        [JsonPropertyName("other_account_secondary_routing_address")]
        public string? OtherAccountSecondaryRoutingAddress { get { return this.OtherAccountSecondaryRoutingAddressOption; } set { this.OtherAccountSecondaryRoutingAddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of OtherBranchRoutingAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OtherBranchRoutingAddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets OtherBranchRoutingAddress
        /// </summary>
        [JsonPropertyName("other_branch_routing_address")]
        public string? OtherBranchRoutingAddress { get { return this.OtherBranchRoutingAddressOption; } set { this.OtherBranchRoutingAddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of OtherBankRoutingScheme
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OtherBankRoutingSchemeOption { get; private set; }

        /// <summary>
        /// Gets or Sets OtherBankRoutingScheme
        /// </summary>
        [JsonPropertyName("other_bank_routing_scheme")]
        public string? OtherBankRoutingScheme { get { return this.OtherBankRoutingSchemeOption; } set { this.OtherBankRoutingSchemeOption = new(value); } }

        /// <summary>
        /// Used to track the state of OtherBranchRoutingScheme
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OtherBranchRoutingSchemeOption { get; private set; }

        /// <summary>
        /// Gets or Sets OtherBranchRoutingScheme
        /// </summary>
        [JsonPropertyName("other_branch_routing_scheme")]
        public string? OtherBranchRoutingScheme { get { return this.OtherBranchRoutingSchemeOption; } set { this.OtherBranchRoutingSchemeOption = new(value); } }

        /// <summary>
        /// Used to track the state of OtherBankRoutingAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OtherBankRoutingAddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets OtherBankRoutingAddress
        /// </summary>
        [JsonPropertyName("other_bank_routing_address")]
        public string? OtherBankRoutingAddress { get { return this.OtherBankRoutingAddressOption; } set { this.OtherBankRoutingAddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of OtherAccountSecondaryRoutingScheme
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OtherAccountSecondaryRoutingSchemeOption { get; private set; }

        /// <summary>
        /// Gets or Sets OtherAccountSecondaryRoutingScheme
        /// </summary>
        [JsonPropertyName("other_account_secondary_routing_scheme")]
        public string? OtherAccountSecondaryRoutingScheme { get { return this.OtherAccountSecondaryRoutingSchemeOption; } set { this.OtherAccountSecondaryRoutingSchemeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateTransactionRequestSimpleRequestTo {\n");
            sb.Append("  OtherAccountRoutingAddress: ").Append(OtherAccountRoutingAddress).Append("\n");
            sb.Append("  OtherAccountRoutingScheme: ").Append(OtherAccountRoutingScheme).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  OtherAccountSecondaryRoutingAddress: ").Append(OtherAccountSecondaryRoutingAddress).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  OtherBranchRoutingAddress: ").Append(OtherBranchRoutingAddress).Append("\n");
            sb.Append("  OtherBankRoutingScheme: ").Append(OtherBankRoutingScheme).Append("\n");
            sb.Append("  OtherBranchRoutingScheme: ").Append(OtherBranchRoutingScheme).Append("\n");
            sb.Append("  OtherBankRoutingAddress: ").Append(OtherBankRoutingAddress).Append("\n");
            sb.Append("  OtherAccountSecondaryRoutingScheme: ").Append(OtherAccountSecondaryRoutingScheme).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateTransactionRequestSimpleRequestTo" />
    /// </summary>
    public class CreateTransactionRequestSimpleRequestToJsonConverter : JsonConverter<CreateTransactionRequestSimpleRequestTo>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateTransactionRequestSimpleRequestTo" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateTransactionRequestSimpleRequestTo Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> otherAccountRoutingAddress = default;
            Option<string?> otherAccountRoutingScheme = default;
            Option<string?> name = default;
            Option<string?> otherAccountSecondaryRoutingAddress = default;
            Option<string?> description = default;
            Option<string?> otherBranchRoutingAddress = default;
            Option<string?> otherBankRoutingScheme = default;
            Option<string?> otherBranchRoutingScheme = default;
            Option<string?> otherBankRoutingAddress = default;
            Option<string?> otherAccountSecondaryRoutingScheme = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "other_account_routing_address":
                            otherAccountRoutingAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "other_account_routing_scheme":
                            otherAccountRoutingScheme = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "other_account_secondary_routing_address":
                            otherAccountSecondaryRoutingAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "other_branch_routing_address":
                            otherBranchRoutingAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "other_bank_routing_scheme":
                            otherBankRoutingScheme = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "other_branch_routing_scheme":
                            otherBranchRoutingScheme = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "other_bank_routing_address":
                            otherBankRoutingAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "other_account_secondary_routing_scheme":
                            otherAccountSecondaryRoutingScheme = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (otherAccountRoutingAddress.IsSet && otherAccountRoutingAddress.Value == null)
                throw new ArgumentNullException(nameof(otherAccountRoutingAddress), "Property is not nullable for class CreateTransactionRequestSimpleRequestTo.");

            if (otherAccountRoutingScheme.IsSet && otherAccountRoutingScheme.Value == null)
                throw new ArgumentNullException(nameof(otherAccountRoutingScheme), "Property is not nullable for class CreateTransactionRequestSimpleRequestTo.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CreateTransactionRequestSimpleRequestTo.");

            if (otherAccountSecondaryRoutingAddress.IsSet && otherAccountSecondaryRoutingAddress.Value == null)
                throw new ArgumentNullException(nameof(otherAccountSecondaryRoutingAddress), "Property is not nullable for class CreateTransactionRequestSimpleRequestTo.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class CreateTransactionRequestSimpleRequestTo.");

            if (otherBranchRoutingAddress.IsSet && otherBranchRoutingAddress.Value == null)
                throw new ArgumentNullException(nameof(otherBranchRoutingAddress), "Property is not nullable for class CreateTransactionRequestSimpleRequestTo.");

            if (otherBankRoutingScheme.IsSet && otherBankRoutingScheme.Value == null)
                throw new ArgumentNullException(nameof(otherBankRoutingScheme), "Property is not nullable for class CreateTransactionRequestSimpleRequestTo.");

            if (otherBranchRoutingScheme.IsSet && otherBranchRoutingScheme.Value == null)
                throw new ArgumentNullException(nameof(otherBranchRoutingScheme), "Property is not nullable for class CreateTransactionRequestSimpleRequestTo.");

            if (otherBankRoutingAddress.IsSet && otherBankRoutingAddress.Value == null)
                throw new ArgumentNullException(nameof(otherBankRoutingAddress), "Property is not nullable for class CreateTransactionRequestSimpleRequestTo.");

            if (otherAccountSecondaryRoutingScheme.IsSet && otherAccountSecondaryRoutingScheme.Value == null)
                throw new ArgumentNullException(nameof(otherAccountSecondaryRoutingScheme), "Property is not nullable for class CreateTransactionRequestSimpleRequestTo.");

            return new CreateTransactionRequestSimpleRequestTo(otherAccountRoutingAddress, otherAccountRoutingScheme, name, otherAccountSecondaryRoutingAddress, description, otherBranchRoutingAddress, otherBankRoutingScheme, otherBranchRoutingScheme, otherBankRoutingAddress, otherAccountSecondaryRoutingScheme);
        }

        /// <summary>
        /// Serializes a <see cref="CreateTransactionRequestSimpleRequestTo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createTransactionRequestSimpleRequestTo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateTransactionRequestSimpleRequestTo createTransactionRequestSimpleRequestTo, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createTransactionRequestSimpleRequestTo, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateTransactionRequestSimpleRequestTo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createTransactionRequestSimpleRequestTo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateTransactionRequestSimpleRequestTo createTransactionRequestSimpleRequestTo, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createTransactionRequestSimpleRequestTo.OtherAccountRoutingAddressOption.IsSet && createTransactionRequestSimpleRequestTo.OtherAccountRoutingAddress == null)
                throw new ArgumentNullException(nameof(createTransactionRequestSimpleRequestTo.OtherAccountRoutingAddress), "Property is required for class CreateTransactionRequestSimpleRequestTo.");

            if (createTransactionRequestSimpleRequestTo.OtherAccountRoutingSchemeOption.IsSet && createTransactionRequestSimpleRequestTo.OtherAccountRoutingScheme == null)
                throw new ArgumentNullException(nameof(createTransactionRequestSimpleRequestTo.OtherAccountRoutingScheme), "Property is required for class CreateTransactionRequestSimpleRequestTo.");

            if (createTransactionRequestSimpleRequestTo.NameOption.IsSet && createTransactionRequestSimpleRequestTo.Name == null)
                throw new ArgumentNullException(nameof(createTransactionRequestSimpleRequestTo.Name), "Property is required for class CreateTransactionRequestSimpleRequestTo.");

            if (createTransactionRequestSimpleRequestTo.OtherAccountSecondaryRoutingAddressOption.IsSet && createTransactionRequestSimpleRequestTo.OtherAccountSecondaryRoutingAddress == null)
                throw new ArgumentNullException(nameof(createTransactionRequestSimpleRequestTo.OtherAccountSecondaryRoutingAddress), "Property is required for class CreateTransactionRequestSimpleRequestTo.");

            if (createTransactionRequestSimpleRequestTo.DescriptionOption.IsSet && createTransactionRequestSimpleRequestTo.Description == null)
                throw new ArgumentNullException(nameof(createTransactionRequestSimpleRequestTo.Description), "Property is required for class CreateTransactionRequestSimpleRequestTo.");

            if (createTransactionRequestSimpleRequestTo.OtherBranchRoutingAddressOption.IsSet && createTransactionRequestSimpleRequestTo.OtherBranchRoutingAddress == null)
                throw new ArgumentNullException(nameof(createTransactionRequestSimpleRequestTo.OtherBranchRoutingAddress), "Property is required for class CreateTransactionRequestSimpleRequestTo.");

            if (createTransactionRequestSimpleRequestTo.OtherBankRoutingSchemeOption.IsSet && createTransactionRequestSimpleRequestTo.OtherBankRoutingScheme == null)
                throw new ArgumentNullException(nameof(createTransactionRequestSimpleRequestTo.OtherBankRoutingScheme), "Property is required for class CreateTransactionRequestSimpleRequestTo.");

            if (createTransactionRequestSimpleRequestTo.OtherBranchRoutingSchemeOption.IsSet && createTransactionRequestSimpleRequestTo.OtherBranchRoutingScheme == null)
                throw new ArgumentNullException(nameof(createTransactionRequestSimpleRequestTo.OtherBranchRoutingScheme), "Property is required for class CreateTransactionRequestSimpleRequestTo.");

            if (createTransactionRequestSimpleRequestTo.OtherBankRoutingAddressOption.IsSet && createTransactionRequestSimpleRequestTo.OtherBankRoutingAddress == null)
                throw new ArgumentNullException(nameof(createTransactionRequestSimpleRequestTo.OtherBankRoutingAddress), "Property is required for class CreateTransactionRequestSimpleRequestTo.");

            if (createTransactionRequestSimpleRequestTo.OtherAccountSecondaryRoutingSchemeOption.IsSet && createTransactionRequestSimpleRequestTo.OtherAccountSecondaryRoutingScheme == null)
                throw new ArgumentNullException(nameof(createTransactionRequestSimpleRequestTo.OtherAccountSecondaryRoutingScheme), "Property is required for class CreateTransactionRequestSimpleRequestTo.");

            if (createTransactionRequestSimpleRequestTo.OtherAccountRoutingAddressOption.IsSet)
                writer.WriteString("other_account_routing_address", createTransactionRequestSimpleRequestTo.OtherAccountRoutingAddress);

            if (createTransactionRequestSimpleRequestTo.OtherAccountRoutingSchemeOption.IsSet)
                writer.WriteString("other_account_routing_scheme", createTransactionRequestSimpleRequestTo.OtherAccountRoutingScheme);

            if (createTransactionRequestSimpleRequestTo.NameOption.IsSet)
                writer.WriteString("name", createTransactionRequestSimpleRequestTo.Name);

            if (createTransactionRequestSimpleRequestTo.OtherAccountSecondaryRoutingAddressOption.IsSet)
                writer.WriteString("other_account_secondary_routing_address", createTransactionRequestSimpleRequestTo.OtherAccountSecondaryRoutingAddress);

            if (createTransactionRequestSimpleRequestTo.DescriptionOption.IsSet)
                writer.WriteString("description", createTransactionRequestSimpleRequestTo.Description);

            if (createTransactionRequestSimpleRequestTo.OtherBranchRoutingAddressOption.IsSet)
                writer.WriteString("other_branch_routing_address", createTransactionRequestSimpleRequestTo.OtherBranchRoutingAddress);

            if (createTransactionRequestSimpleRequestTo.OtherBankRoutingSchemeOption.IsSet)
                writer.WriteString("other_bank_routing_scheme", createTransactionRequestSimpleRequestTo.OtherBankRoutingScheme);

            if (createTransactionRequestSimpleRequestTo.OtherBranchRoutingSchemeOption.IsSet)
                writer.WriteString("other_branch_routing_scheme", createTransactionRequestSimpleRequestTo.OtherBranchRoutingScheme);

            if (createTransactionRequestSimpleRequestTo.OtherBankRoutingAddressOption.IsSet)
                writer.WriteString("other_bank_routing_address", createTransactionRequestSimpleRequestTo.OtherBankRoutingAddress);

            if (createTransactionRequestSimpleRequestTo.OtherAccountSecondaryRoutingSchemeOption.IsSet)
                writer.WriteString("other_account_secondary_routing_scheme", createTransactionRequestSimpleRequestTo.OtherAccountSecondaryRoutingScheme);
        }
    }
}
