// <auto-generated>
/*
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenBankProject.Client;

namespace OpenBankProject.Model
{
    /// <summary>
    /// GetFeaturedApiCollectionsAdmin200Response
    /// </summary>
    public partial class GetFeaturedApiCollectionsAdmin200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetFeaturedApiCollectionsAdmin200Response" /> class.
        /// </summary>
        /// <param name="featuredApiCollections">featuredApiCollections</param>
        [JsonConstructor]
        public GetFeaturedApiCollectionsAdmin200Response(Option<List<GetFeaturedApiCollectionsAdmin200ResponseFeaturedApiCollectionsInner>?> featuredApiCollections = default)
        {
            FeaturedApiCollectionsOption = featuredApiCollections;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of FeaturedApiCollections
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<GetFeaturedApiCollectionsAdmin200ResponseFeaturedApiCollectionsInner>?> FeaturedApiCollectionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets FeaturedApiCollections
        /// </summary>
        [JsonPropertyName("featured_api_collections")]
        public List<GetFeaturedApiCollectionsAdmin200ResponseFeaturedApiCollectionsInner>? FeaturedApiCollections { get { return this.FeaturedApiCollectionsOption; } set { this.FeaturedApiCollectionsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetFeaturedApiCollectionsAdmin200Response {\n");
            sb.Append("  FeaturedApiCollections: ").Append(FeaturedApiCollections).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetFeaturedApiCollectionsAdmin200Response" />
    /// </summary>
    public class GetFeaturedApiCollectionsAdmin200ResponseJsonConverter : JsonConverter<GetFeaturedApiCollectionsAdmin200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetFeaturedApiCollectionsAdmin200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetFeaturedApiCollectionsAdmin200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<GetFeaturedApiCollectionsAdmin200ResponseFeaturedApiCollectionsInner>?> featuredApiCollections = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "featured_api_collections":
                            featuredApiCollections = new Option<List<GetFeaturedApiCollectionsAdmin200ResponseFeaturedApiCollectionsInner>?>(JsonSerializer.Deserialize<List<GetFeaturedApiCollectionsAdmin200ResponseFeaturedApiCollectionsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (featuredApiCollections.IsSet && featuredApiCollections.Value == null)
                throw new ArgumentNullException(nameof(featuredApiCollections), "Property is not nullable for class GetFeaturedApiCollectionsAdmin200Response.");

            return new GetFeaturedApiCollectionsAdmin200Response(featuredApiCollections);
        }

        /// <summary>
        /// Serializes a <see cref="GetFeaturedApiCollectionsAdmin200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getFeaturedApiCollectionsAdmin200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetFeaturedApiCollectionsAdmin200Response getFeaturedApiCollectionsAdmin200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getFeaturedApiCollectionsAdmin200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetFeaturedApiCollectionsAdmin200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getFeaturedApiCollectionsAdmin200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetFeaturedApiCollectionsAdmin200Response getFeaturedApiCollectionsAdmin200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getFeaturedApiCollectionsAdmin200Response.FeaturedApiCollectionsOption.IsSet && getFeaturedApiCollectionsAdmin200Response.FeaturedApiCollections == null)
                throw new ArgumentNullException(nameof(getFeaturedApiCollectionsAdmin200Response.FeaturedApiCollections), "Property is required for class GetFeaturedApiCollectionsAdmin200Response.");

            if (getFeaturedApiCollectionsAdmin200Response.FeaturedApiCollectionsOption.IsSet)
            {
                writer.WritePropertyName("featured_api_collections");
                JsonSerializer.Serialize(writer, getFeaturedApiCollectionsAdmin200Response.FeaturedApiCollections, jsonSerializerOptions);
            }
        }
    }
}
