// <auto-generated>
/*
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenBankProject.Client;

namespace OpenBankProject.Model
{
    /// <summary>
    /// GetMandate200Response
    /// </summary>
    public partial class GetMandate200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMandate200Response" /> class.
        /// </summary>
        /// <param name="createdByUserId">createdByUserId</param>
        /// <param name="customerId">customerId</param>
        /// <param name="description">description</param>
        /// <param name="updatedByUserId">updatedByUserId</param>
        /// <param name="bankId">bankId</param>
        /// <param name="accountId">accountId</param>
        /// <param name="legalText">legalText</param>
        /// <param name="status">status</param>
        /// <param name="validFrom">validFrom</param>
        /// <param name="mandateId">mandateId</param>
        /// <param name="validTo">validTo</param>
        /// <param name="mandateReference">mandateReference</param>
        /// <param name="mandateName">mandateName</param>
        [JsonConstructor]
        public GetMandate200Response(Option<string?> createdByUserId = default, Option<string?> customerId = default, Option<string?> description = default, Option<DateTime?> updatedByUserId = default, Option<string?> bankId = default, Option<string?> accountId = default, Option<string?> legalText = default, Option<string?> status = default, Option<string?> validFrom = default, Option<DateTime?> mandateId = default, Option<string?> validTo = default, Option<DateTime?> mandateReference = default, Option<DateTime?> mandateName = default)
        {
            CreatedByUserIdOption = createdByUserId;
            CustomerIdOption = customerId;
            DescriptionOption = description;
            UpdatedByUserIdOption = updatedByUserId;
            BankIdOption = bankId;
            AccountIdOption = accountId;
            LegalTextOption = legalText;
            StatusOption = status;
            ValidFromOption = validFrom;
            MandateIdOption = mandateId;
            ValidToOption = validTo;
            MandateReferenceOption = mandateReference;
            MandateNameOption = mandateName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of CreatedByUserId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CreatedByUserIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedByUserId
        /// </summary>
        [JsonPropertyName("created_by_user_id")]
        public string? CreatedByUserId { get { return this.CreatedByUserIdOption; } set { this.CreatedByUserIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomerId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CustomerIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>
        [JsonPropertyName("customer_id")]
        public string? CustomerId { get { return this.CustomerIdOption; } set { this.CustomerIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdatedByUserId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> UpdatedByUserIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdatedByUserId
        /// </summary>
        [JsonPropertyName("updated_by_user_id")]
        public DateTime? UpdatedByUserId { get { return this.UpdatedByUserIdOption; } set { this.UpdatedByUserIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of BankId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BankIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets BankId
        /// </summary>
        [JsonPropertyName("bank_id")]
        public string? BankId { get { return this.BankIdOption; } set { this.BankIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of AccountId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AccountIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [JsonPropertyName("account_id")]
        public string? AccountId { get { return this.AccountIdOption; } set { this.AccountIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of LegalText
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LegalTextOption { get; private set; }

        /// <summary>
        /// Gets or Sets LegalText
        /// </summary>
        [JsonPropertyName("legal_text")]
        public string? LegalText { get { return this.LegalTextOption; } set { this.LegalTextOption = new(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of ValidFrom
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ValidFromOption { get; private set; }

        /// <summary>
        /// Gets or Sets ValidFrom
        /// </summary>
        [JsonPropertyName("valid_from")]
        public string? ValidFrom { get { return this.ValidFromOption; } set { this.ValidFromOption = new(value); } }

        /// <summary>
        /// Used to track the state of MandateId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> MandateIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets MandateId
        /// </summary>
        [JsonPropertyName("mandate_id")]
        public DateTime? MandateId { get { return this.MandateIdOption; } set { this.MandateIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ValidTo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ValidToOption { get; private set; }

        /// <summary>
        /// Gets or Sets ValidTo
        /// </summary>
        [JsonPropertyName("valid_to")]
        public string? ValidTo { get { return this.ValidToOption; } set { this.ValidToOption = new(value); } }

        /// <summary>
        /// Used to track the state of MandateReference
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> MandateReferenceOption { get; private set; }

        /// <summary>
        /// Gets or Sets MandateReference
        /// </summary>
        [JsonPropertyName("mandate_reference")]
        public DateTime? MandateReference { get { return this.MandateReferenceOption; } set { this.MandateReferenceOption = new(value); } }

        /// <summary>
        /// Used to track the state of MandateName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> MandateNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets MandateName
        /// </summary>
        [JsonPropertyName("mandate_name")]
        public DateTime? MandateName { get { return this.MandateNameOption; } set { this.MandateNameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMandate200Response {\n");
            sb.Append("  CreatedByUserId: ").Append(CreatedByUserId).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  UpdatedByUserId: ").Append(UpdatedByUserId).Append("\n");
            sb.Append("  BankId: ").Append(BankId).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  LegalText: ").Append(LegalText).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ValidFrom: ").Append(ValidFrom).Append("\n");
            sb.Append("  MandateId: ").Append(MandateId).Append("\n");
            sb.Append("  ValidTo: ").Append(ValidTo).Append("\n");
            sb.Append("  MandateReference: ").Append(MandateReference).Append("\n");
            sb.Append("  MandateName: ").Append(MandateName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetMandate200Response" />
    /// </summary>
    public class GetMandate200ResponseJsonConverter : JsonConverter<GetMandate200Response>
    {
        /// <summary>
        /// The format to use to serialize UpdatedByUserId
        /// </summary>
        public static string UpdatedByUserIdFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize MandateId
        /// </summary>
        public static string MandateIdFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize MandateReference
        /// </summary>
        public static string MandateReferenceFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize MandateName
        /// </summary>
        public static string MandateNameFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="GetMandate200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetMandate200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> createdByUserId = default;
            Option<string?> customerId = default;
            Option<string?> description = default;
            Option<DateTime?> updatedByUserId = default;
            Option<string?> bankId = default;
            Option<string?> accountId = default;
            Option<string?> legalText = default;
            Option<string?> status = default;
            Option<string?> validFrom = default;
            Option<DateTime?> mandateId = default;
            Option<string?> validTo = default;
            Option<DateTime?> mandateReference = default;
            Option<DateTime?> mandateName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "created_by_user_id":
                            createdByUserId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "customer_id":
                            customerId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "updated_by_user_id":
                            updatedByUserId = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "bank_id":
                            bankId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "account_id":
                            accountId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "legal_text":
                            legalText = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "valid_from":
                            validFrom = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "mandate_id":
                            mandateId = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "valid_to":
                            validTo = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "mandate_reference":
                            mandateReference = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "mandate_name":
                            mandateName = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (createdByUserId.IsSet && createdByUserId.Value == null)
                throw new ArgumentNullException(nameof(createdByUserId), "Property is not nullable for class GetMandate200Response.");

            if (customerId.IsSet && customerId.Value == null)
                throw new ArgumentNullException(nameof(customerId), "Property is not nullable for class GetMandate200Response.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class GetMandate200Response.");

            if (updatedByUserId.IsSet && updatedByUserId.Value == null)
                throw new ArgumentNullException(nameof(updatedByUserId), "Property is not nullable for class GetMandate200Response.");

            if (bankId.IsSet && bankId.Value == null)
                throw new ArgumentNullException(nameof(bankId), "Property is not nullable for class GetMandate200Response.");

            if (accountId.IsSet && accountId.Value == null)
                throw new ArgumentNullException(nameof(accountId), "Property is not nullable for class GetMandate200Response.");

            if (legalText.IsSet && legalText.Value == null)
                throw new ArgumentNullException(nameof(legalText), "Property is not nullable for class GetMandate200Response.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class GetMandate200Response.");

            if (validFrom.IsSet && validFrom.Value == null)
                throw new ArgumentNullException(nameof(validFrom), "Property is not nullable for class GetMandate200Response.");

            if (mandateId.IsSet && mandateId.Value == null)
                throw new ArgumentNullException(nameof(mandateId), "Property is not nullable for class GetMandate200Response.");

            if (validTo.IsSet && validTo.Value == null)
                throw new ArgumentNullException(nameof(validTo), "Property is not nullable for class GetMandate200Response.");

            if (mandateReference.IsSet && mandateReference.Value == null)
                throw new ArgumentNullException(nameof(mandateReference), "Property is not nullable for class GetMandate200Response.");

            if (mandateName.IsSet && mandateName.Value == null)
                throw new ArgumentNullException(nameof(mandateName), "Property is not nullable for class GetMandate200Response.");

            return new GetMandate200Response(createdByUserId, customerId, description, updatedByUserId, bankId, accountId, legalText, status, validFrom, mandateId, validTo, mandateReference, mandateName);
        }

        /// <summary>
        /// Serializes a <see cref="GetMandate200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getMandate200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetMandate200Response getMandate200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getMandate200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetMandate200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getMandate200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetMandate200Response getMandate200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getMandate200Response.CreatedByUserIdOption.IsSet && getMandate200Response.CreatedByUserId == null)
                throw new ArgumentNullException(nameof(getMandate200Response.CreatedByUserId), "Property is required for class GetMandate200Response.");

            if (getMandate200Response.CustomerIdOption.IsSet && getMandate200Response.CustomerId == null)
                throw new ArgumentNullException(nameof(getMandate200Response.CustomerId), "Property is required for class GetMandate200Response.");

            if (getMandate200Response.DescriptionOption.IsSet && getMandate200Response.Description == null)
                throw new ArgumentNullException(nameof(getMandate200Response.Description), "Property is required for class GetMandate200Response.");

            if (getMandate200Response.BankIdOption.IsSet && getMandate200Response.BankId == null)
                throw new ArgumentNullException(nameof(getMandate200Response.BankId), "Property is required for class GetMandate200Response.");

            if (getMandate200Response.AccountIdOption.IsSet && getMandate200Response.AccountId == null)
                throw new ArgumentNullException(nameof(getMandate200Response.AccountId), "Property is required for class GetMandate200Response.");

            if (getMandate200Response.LegalTextOption.IsSet && getMandate200Response.LegalText == null)
                throw new ArgumentNullException(nameof(getMandate200Response.LegalText), "Property is required for class GetMandate200Response.");

            if (getMandate200Response.StatusOption.IsSet && getMandate200Response.Status == null)
                throw new ArgumentNullException(nameof(getMandate200Response.Status), "Property is required for class GetMandate200Response.");

            if (getMandate200Response.ValidFromOption.IsSet && getMandate200Response.ValidFrom == null)
                throw new ArgumentNullException(nameof(getMandate200Response.ValidFrom), "Property is required for class GetMandate200Response.");

            if (getMandate200Response.ValidToOption.IsSet && getMandate200Response.ValidTo == null)
                throw new ArgumentNullException(nameof(getMandate200Response.ValidTo), "Property is required for class GetMandate200Response.");

            if (getMandate200Response.CreatedByUserIdOption.IsSet)
                writer.WriteString("created_by_user_id", getMandate200Response.CreatedByUserId);

            if (getMandate200Response.CustomerIdOption.IsSet)
                writer.WriteString("customer_id", getMandate200Response.CustomerId);

            if (getMandate200Response.DescriptionOption.IsSet)
                writer.WriteString("description", getMandate200Response.Description);

            if (getMandate200Response.UpdatedByUserIdOption.IsSet)
                writer.WriteString("updated_by_user_id", getMandate200Response.UpdatedByUserIdOption.Value!.Value.ToString(UpdatedByUserIdFormat));

            if (getMandate200Response.BankIdOption.IsSet)
                writer.WriteString("bank_id", getMandate200Response.BankId);

            if (getMandate200Response.AccountIdOption.IsSet)
                writer.WriteString("account_id", getMandate200Response.AccountId);

            if (getMandate200Response.LegalTextOption.IsSet)
                writer.WriteString("legal_text", getMandate200Response.LegalText);

            if (getMandate200Response.StatusOption.IsSet)
                writer.WriteString("status", getMandate200Response.Status);

            if (getMandate200Response.ValidFromOption.IsSet)
                writer.WriteString("valid_from", getMandate200Response.ValidFrom);

            if (getMandate200Response.MandateIdOption.IsSet)
                writer.WriteString("mandate_id", getMandate200Response.MandateIdOption.Value!.Value.ToString(MandateIdFormat));

            if (getMandate200Response.ValidToOption.IsSet)
                writer.WriteString("valid_to", getMandate200Response.ValidTo);

            if (getMandate200Response.MandateReferenceOption.IsSet)
                writer.WriteString("mandate_reference", getMandate200Response.MandateReferenceOption.Value!.Value.ToString(MandateReferenceFormat));

            if (getMandate200Response.MandateNameOption.IsSet)
                writer.WriteString("mandate_name", getMandate200Response.MandateNameOption.Value!.Value.ToString(MandateNameFormat));
        }
    }
}
