// <auto-generated>
/*
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenBankProject.Client;

namespace OpenBankProject.Model
{
    /// <summary>
    /// PublishSignalMessage200Response
    /// </summary>
    public partial class PublishSignalMessage200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublishSignalMessage200Response" /> class.
        /// </summary>
        /// <param name="messageId">messageId</param>
        /// <param name="timestamp">timestamp</param>
        /// <param name="channelMessageCount">channelMessageCount</param>
        /// <param name="channelName">channelName</param>
        [JsonConstructor]
        public PublishSignalMessage200Response(Option<string?> messageId = default, Option<string?> timestamp = default, Option<int?> channelMessageCount = default, Option<string?> channelName = default)
        {
            MessageIdOption = messageId;
            TimestampOption = timestamp;
            ChannelMessageCountOption = channelMessageCount;
            ChannelNameOption = channelName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of MessageId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets MessageId
        /// </summary>
        [JsonPropertyName("message_id")]
        public string? MessageId { get { return this.MessageIdOption; } set { this.MessageIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Timestamp
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TimestampOption { get; private set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [JsonPropertyName("timestamp")]
        public string? Timestamp { get { return this.TimestampOption; } set { this.TimestampOption = new(value); } }

        /// <summary>
        /// Used to track the state of ChannelMessageCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ChannelMessageCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets ChannelMessageCount
        /// </summary>
        [JsonPropertyName("channel_message_count")]
        public int? ChannelMessageCount { get { return this.ChannelMessageCountOption; } set { this.ChannelMessageCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of ChannelName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ChannelNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ChannelName
        /// </summary>
        [JsonPropertyName("channel_name")]
        public string? ChannelName { get { return this.ChannelNameOption; } set { this.ChannelNameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PublishSignalMessage200Response {\n");
            sb.Append("  MessageId: ").Append(MessageId).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  ChannelMessageCount: ").Append(ChannelMessageCount).Append("\n");
            sb.Append("  ChannelName: ").Append(ChannelName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PublishSignalMessage200Response" />
    /// </summary>
    public class PublishSignalMessage200ResponseJsonConverter : JsonConverter<PublishSignalMessage200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="PublishSignalMessage200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PublishSignalMessage200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> messageId = default;
            Option<string?> timestamp = default;
            Option<int?> channelMessageCount = default;
            Option<string?> channelName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "message_id":
                            messageId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "timestamp":
                            timestamp = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "channel_message_count":
                            channelMessageCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "channel_name":
                            channelName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (messageId.IsSet && messageId.Value == null)
                throw new ArgumentNullException(nameof(messageId), "Property is not nullable for class PublishSignalMessage200Response.");

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class PublishSignalMessage200Response.");

            if (channelMessageCount.IsSet && channelMessageCount.Value == null)
                throw new ArgumentNullException(nameof(channelMessageCount), "Property is not nullable for class PublishSignalMessage200Response.");

            if (channelName.IsSet && channelName.Value == null)
                throw new ArgumentNullException(nameof(channelName), "Property is not nullable for class PublishSignalMessage200Response.");

            return new PublishSignalMessage200Response(messageId, timestamp, channelMessageCount, channelName);
        }

        /// <summary>
        /// Serializes a <see cref="PublishSignalMessage200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="publishSignalMessage200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PublishSignalMessage200Response publishSignalMessage200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, publishSignalMessage200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PublishSignalMessage200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="publishSignalMessage200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PublishSignalMessage200Response publishSignalMessage200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (publishSignalMessage200Response.MessageIdOption.IsSet && publishSignalMessage200Response.MessageId == null)
                throw new ArgumentNullException(nameof(publishSignalMessage200Response.MessageId), "Property is required for class PublishSignalMessage200Response.");

            if (publishSignalMessage200Response.TimestampOption.IsSet && publishSignalMessage200Response.Timestamp == null)
                throw new ArgumentNullException(nameof(publishSignalMessage200Response.Timestamp), "Property is required for class PublishSignalMessage200Response.");

            if (publishSignalMessage200Response.ChannelNameOption.IsSet && publishSignalMessage200Response.ChannelName == null)
                throw new ArgumentNullException(nameof(publishSignalMessage200Response.ChannelName), "Property is required for class PublishSignalMessage200Response.");

            if (publishSignalMessage200Response.MessageIdOption.IsSet)
                writer.WriteString("message_id", publishSignalMessage200Response.MessageId);

            if (publishSignalMessage200Response.TimestampOption.IsSet)
                writer.WriteString("timestamp", publishSignalMessage200Response.Timestamp);

            if (publishSignalMessage200Response.ChannelMessageCountOption.IsSet)
                writer.WriteNumber("channel_message_count", publishSignalMessage200Response.ChannelMessageCountOption.Value!.Value);

            if (publishSignalMessage200Response.ChannelNameOption.IsSet)
                writer.WriteString("channel_name", publishSignalMessage200Response.ChannelName);
        }
    }
}
