# coding: utf-8

"""
    Open Bank Project API v6.0.0

    The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API

    The version of the OpenAPI document: 6.0.0
    Contact: contact@tesobe.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from obp_python.api.dynamic_endpoint_manage_api import DynamicEndpointManageApi


class TestDynamicEndpointManageApi(unittest.TestCase):
    """DynamicEndpointManageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DynamicEndpointManageApi()

    def tearDown(self) -> None:
        pass

    def test_create_bank_level_dynamic_endpoint(self) -> None:
        """Test case for create_bank_level_dynamic_endpoint

        Create Bank Level Dynamic Endpoint
        """
        pass

    def test_create_dynamic_endpoint(self) -> None:
        """Test case for create_dynamic_endpoint

        Create Dynamic Endpoint
        """
        pass

    def test_delete_bank_level_dynamic_endpoint(self) -> None:
        """Test case for delete_bank_level_dynamic_endpoint

         Delete Bank Level Dynamic Endpoint
        """
        pass

    def test_delete_dynamic_endpoint(self) -> None:
        """Test case for delete_dynamic_endpoint

         Delete Dynamic Endpoint
        """
        pass

    def test_delete_my_dynamic_endpoint(self) -> None:
        """Test case for delete_my_dynamic_endpoint

        Delete My Dynamic Endpoint
        """
        pass

    def test_get_bank_level_dynamic_endpoint(self) -> None:
        """Test case for get_bank_level_dynamic_endpoint

         Get Bank Level Dynamic Endpoint
        """
        pass

    def test_get_bank_level_dynamic_endpoints(self) -> None:
        """Test case for get_bank_level_dynamic_endpoints

        Get Bank Level Dynamic Endpoints
        """
        pass

    def test_get_dynamic_endpoint(self) -> None:
        """Test case for get_dynamic_endpoint

        Get Dynamic Endpoint
        """
        pass

    def test_get_dynamic_endpoints(self) -> None:
        """Test case for get_dynamic_endpoints

         Get Dynamic Endpoints
        """
        pass

    def test_get_my_dynamic_endpoints(self) -> None:
        """Test case for get_my_dynamic_endpoints

        Get My Dynamic Endpoints
        """
        pass

    def test_update_bank_level_dynamic_endpoint_host(self) -> None:
        """Test case for update_bank_level_dynamic_endpoint_host

         Update Bank Level Dynamic Endpoint Host
        """
        pass

    def test_update_dynamic_endpoint_host(self) -> None:
        """Test case for update_dynamic_endpoint_host

         Update Dynamic Endpoint Host
        """
        pass


if __name__ == '__main__':
    unittest.main()
