# coding: utf-8

"""
    Open Bank Project API v6.0.0

    The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API

    The version of the OpenAPI document: 6.0.0
    Contact: contact@tesobe.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from obp_python.models.get_my_customers_at_bank200_response_customers_inner_face_image import GetMyCustomersAtBank200ResponseCustomersInnerFaceImage

class TestGetMyCustomersAtBank200ResponseCustomersInnerFaceImage(unittest.TestCase):
    """GetMyCustomersAtBank200ResponseCustomersInnerFaceImage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMyCustomersAtBank200ResponseCustomersInnerFaceImage:
        """Test GetMyCustomersAtBank200ResponseCustomersInnerFaceImage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMyCustomersAtBank200ResponseCustomersInnerFaceImage`
        """
        model = GetMyCustomersAtBank200ResponseCustomersInnerFaceImage()
        if include_optional:
            return GetMyCustomersAtBank200ResponseCustomersInnerFaceImage(
                url = '',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetMyCustomersAtBank200ResponseCustomersInnerFaceImage(
        )
        """

    def testGetMyCustomersAtBank200ResponseCustomersInnerFaceImage(self):
        """Test GetMyCustomersAtBank200ResponseCustomersInnerFaceImage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
