# coding: utf-8

"""
    Open Bank Project API v6.0.0

    The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API

    The version of the OpenAPI document: 6.0.0
    Contact: contact@tesobe.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from obp_python.models.public_accounts_all_banks200_response import PublicAccountsAllBanks200Response

class TestPublicAccountsAllBanks200Response(unittest.TestCase):
    """PublicAccountsAllBanks200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicAccountsAllBanks200Response:
        """Test PublicAccountsAllBanks200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicAccountsAllBanks200Response`
        """
        model = PublicAccountsAllBanks200Response()
        if include_optional:
            return PublicAccountsAllBanks200Response(
                accounts = [
                    obp_python.models.public_accounts_all_banks_200_response_accounts_inner.publicAccountsAllBanks_200_response_accounts_inner(
                        label = '', 
                        id = '', 
                        bank_id = '', 
                        views_available = [
                            obp_python.models.public_accounts_all_banks_200_response_accounts_inner_views_available_inner.publicAccountsAllBanks_200_response_accounts_inner_views_available_inner(
                                short_name = '', 
                                id = '', 
                                is_public = True, )
                            ], )
                    ]
            )
        else:
            return PublicAccountsAllBanks200Response(
        )
        """

    def testPublicAccountsAllBanks200Response(self):
        """Test PublicAccountsAllBanks200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
