# coding: utf-8

"""
    Open Bank Project API v6.0.0

    The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API

    The version of the OpenAPI document: 6.0.0
    Contact: contact@tesobe.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from obp_python.models.get_transaction_request_types200_response import GetTransactionRequestTypes200Response

class TestGetTransactionRequestTypes200Response(unittest.TestCase):
    """GetTransactionRequestTypes200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTransactionRequestTypes200Response:
        """Test GetTransactionRequestTypes200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTransactionRequestTypes200Response`
        """
        model = GetTransactionRequestTypes200Response()
        if include_optional:
            return GetTransactionRequestTypes200Response(
                transaction_request_types = [
                    obp_python.models.get_transaction_request_types_200_response_transaction_request_types_inner.getTransactionRequestTypes_200_response_transaction_request_types_inner(
                        charge = obp_python.models.create_transaction_request_counterparty_200_response_charge.createTransactionRequestCounterparty_200_response_charge(
                            summary = '', 
                            value = obp_python.models.get_my_customers_at_bank_200_response_customers_inner_credit_limit.getMyCustomersAtBank_200_response_customers_inner_credit_limit(
                                currency = '', 
                                amount = '', ), ), 
                        value = '', )
                    ]
            )
        else:
            return GetTransactionRequestTypes200Response(
        )
        """

    def testGetTransactionRequestTypes200Response(self):
        """Test GetTransactionRequestTypes200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
