# coding: utf-8

"""
    Open Bank Project API v6.0.0

    The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API

    The version of the OpenAPI document: 6.0.0
    Contact: contact@tesobe.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from obp_python.models.build_dynamic_endpoint_template_request import BuildDynamicEndpointTemplateRequest

class TestBuildDynamicEndpointTemplateRequest(unittest.TestCase):
    """BuildDynamicEndpointTemplateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BuildDynamicEndpointTemplateRequest:
        """Test BuildDynamicEndpointTemplateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BuildDynamicEndpointTemplateRequest`
        """
        model = BuildDynamicEndpointTemplateRequest()
        if include_optional:
            return BuildDynamicEndpointTemplateRequest(
                request_verb = '',
                example_request_body = obp_python.models.get_bank_level_dynamic_resource_doc_200_response_example_request_body.getBankLevelDynamicResourceDoc_200_response_example_request_body(
                    name = '', 
                    age = 56, 
                    hobby = [
                        obp_python.models.get_bank_level_dynamic_resource_doc_200_response_success_response_body__optional_fields__inner.getBankLevelDynamicResourceDoc_200_response_success_response_body__optional_fields__inner(
                            s = '', )
                        ], 
                    _optional_fields_ = [
                        obp_python.models.get_bank_level_dynamic_resource_doc_200_response_success_response_body__optional_fields__inner.getBankLevelDynamicResourceDoc_200_response_success_response_body__optional_fields__inner(
                            s = '', )
                        ], ),
                success_response_body = obp_python.models.get_bank_level_dynamic_resource_doc_200_response_success_response_body.getBankLevelDynamicResourceDoc_200_response_success_response_body(
                    name = '', 
                    _optional_fields_ = [
                        obp_python.models.get_bank_level_dynamic_resource_doc_200_response_success_response_body__optional_fields__inner.getBankLevelDynamicResourceDoc_200_response_success_response_body__optional_fields__inner(
                            s = '', )
                        ], 
                    age = 56, 
                    hobby = [
                        obp_python.models.get_bank_level_dynamic_resource_doc_200_response_success_response_body__optional_fields__inner.getBankLevelDynamicResourceDoc_200_response_success_response_body__optional_fields__inner(
                            s = '', )
                        ], 
                    my_user_id = '', ),
                request_url = ''
            )
        else:
            return BuildDynamicEndpointTemplateRequest(
        )
        """

    def testBuildDynamicEndpointTemplateRequest(self):
        """Test BuildDynamicEndpointTemplateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
