# coding: utf-8

"""
    Open Bank Project API v6.0.0

    The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API

    The version of the OpenAPI document: 6.0.0
    Contact: contact@tesobe.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from obp_python.models.get_roles200_response import GetRoles200Response

class TestGetRoles200Response(unittest.TestCase):
    """GetRoles200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRoles200Response:
        """Test GetRoles200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRoles200Response`
        """
        model = GetRoles200Response()
        if include_optional:
            return GetRoles200Response(
                roles = [
                    obp_python.models.get_roles_200_response_roles_inner.getRoles_200_response_roles_inner(
                        role = '', 
                        requires_bank_id = True, )
                    ]
            )
        else:
            return GetRoles200Response(
        )
        """

    def testGetRoles200Response(self):
        """Test GetRoles200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
