# coding: utf-8

"""
    Open Bank Project API v6.0.0

    The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API

    The version of the OpenAPI document: 6.0.0
    Contact: contact@tesobe.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from obp_python.models.get_kyc_media200_response import GetKycMedia200Response

class TestGetKycMedia200Response(unittest.TestCase):
    """GetKycMedia200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetKycMedia200Response:
        """Test GetKycMedia200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetKycMedia200Response`
        """
        model = GetKycMedia200Response()
        if include_optional:
            return GetKycMedia200Response(
                medias = [
                    obp_python.models.add_kyc_media_200_response.addKycMedia_200_response(
                        customer_id = '', 
                        url = '', 
                        customer_number = '', 
                        bank_id = '', 
                        id = '', 
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        relates_to_kyc_document_id = '', 
                        relates_to_kyc_check_id = '', 
                        type = '', )
                    ]
            )
        else:
            return GetKycMedia200Response(
        )
        """

    def testGetKycMedia200Response(self):
        """Test GetKycMedia200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
