=begin
#Open Bank Project API v6.0.0

#The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API

The version of the OpenAPI document: 6.0.0
Contact: contact@tesobe.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenBankProject::Config200ResponseScopes
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenBankProject::Config200ResponseScopes do
  #let(:instance) { OpenBankProject::Config200ResponseScopes.new }

  describe 'test an instance of Config200ResponseScopes' do
    it 'should create an instance of Config200ResponseScopes' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenBankProject::Config200ResponseScopes)
    end
  end

  describe 'test attribute "require_scopes_for_all_roles"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "require_scopes_for_listed_roles"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
