/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetRegulatedEntityById200ResponseAttributesInner } from './GetRegulatedEntityById200ResponseAttributesInner';
import {
    GetRegulatedEntityById200ResponseAttributesInnerFromJSON,
    GetRegulatedEntityById200ResponseAttributesInnerFromJSONTyped,
    GetRegulatedEntityById200ResponseAttributesInnerToJSON,
    GetRegulatedEntityById200ResponseAttributesInnerToJSONTyped,
} from './GetRegulatedEntityById200ResponseAttributesInner';
import type { GetRegulatedEntityById200ResponseServicesInner } from './GetRegulatedEntityById200ResponseServicesInner';
import {
    GetRegulatedEntityById200ResponseServicesInnerFromJSON,
    GetRegulatedEntityById200ResponseServicesInnerFromJSONTyped,
    GetRegulatedEntityById200ResponseServicesInnerToJSON,
    GetRegulatedEntityById200ResponseServicesInnerToJSONTyped,
} from './GetRegulatedEntityById200ResponseServicesInner';

/**
 * 
 * @export
 * @interface CreateRegulatedEntityRequest
 */
export interface CreateRegulatedEntityRequest {
    /**
     * 
     * @type {Array<GetRegulatedEntityById200ResponseServicesInner>}
     * @memberof CreateRegulatedEntityRequest
     */
    services?: Array<GetRegulatedEntityById200ResponseServicesInner>;
    /**
     * 
     * @type {string}
     * @memberof CreateRegulatedEntityRequest
     */
    entityCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegulatedEntityRequest
     */
    entityWebSite?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegulatedEntityRequest
     */
    entityCountry?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegulatedEntityRequest
     */
    entityCertificatePublicKey?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegulatedEntityRequest
     */
    entityType?: string;
    /**
     * 
     * @type {Array<GetRegulatedEntityById200ResponseAttributesInner>}
     * @memberof CreateRegulatedEntityRequest
     */
    attributes?: Array<GetRegulatedEntityById200ResponseAttributesInner>;
    /**
     * 
     * @type {string}
     * @memberof CreateRegulatedEntityRequest
     */
    entityPostCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegulatedEntityRequest
     */
    entityName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegulatedEntityRequest
     */
    entityTownCity?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegulatedEntityRequest
     */
    entityAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegulatedEntityRequest
     */
    certificateAuthorityCaOwnerId?: string;
}

/**
 * Check if a given object implements the CreateRegulatedEntityRequest interface.
 */
export function instanceOfCreateRegulatedEntityRequest(value: object): value is CreateRegulatedEntityRequest {
    return true;
}

export function CreateRegulatedEntityRequestFromJSON(json: any): CreateRegulatedEntityRequest {
    return CreateRegulatedEntityRequestFromJSONTyped(json, false);
}

export function CreateRegulatedEntityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRegulatedEntityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'services': json['services'] == null ? undefined : ((json['services'] as Array<any>).map(GetRegulatedEntityById200ResponseServicesInnerFromJSON)),
        'entityCode': json['entity_code'] == null ? undefined : json['entity_code'],
        'entityWebSite': json['entity_web_site'] == null ? undefined : json['entity_web_site'],
        'entityCountry': json['entity_country'] == null ? undefined : json['entity_country'],
        'entityCertificatePublicKey': json['entity_certificate_public_key'] == null ? undefined : json['entity_certificate_public_key'],
        'entityType': json['entity_type'] == null ? undefined : json['entity_type'],
        'attributes': json['attributes'] == null ? undefined : ((json['attributes'] as Array<any>).map(GetRegulatedEntityById200ResponseAttributesInnerFromJSON)),
        'entityPostCode': json['entity_post_code'] == null ? undefined : json['entity_post_code'],
        'entityName': json['entity_name'] == null ? undefined : json['entity_name'],
        'entityTownCity': json['entity_town_city'] == null ? undefined : json['entity_town_city'],
        'entityAddress': json['entity_address'] == null ? undefined : json['entity_address'],
        'certificateAuthorityCaOwnerId': json['certificate_authority_ca_owner_id'] == null ? undefined : json['certificate_authority_ca_owner_id'],
    };
}

export function CreateRegulatedEntityRequestToJSON(json: any): CreateRegulatedEntityRequest {
    return CreateRegulatedEntityRequestToJSONTyped(json, false);
}

export function CreateRegulatedEntityRequestToJSONTyped(value?: CreateRegulatedEntityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'services': value['services'] == null ? undefined : ((value['services'] as Array<any>).map(GetRegulatedEntityById200ResponseServicesInnerToJSON)),
        'entity_code': value['entityCode'],
        'entity_web_site': value['entityWebSite'],
        'entity_country': value['entityCountry'],
        'entity_certificate_public_key': value['entityCertificatePublicKey'],
        'entity_type': value['entityType'],
        'attributes': value['attributes'] == null ? undefined : ((value['attributes'] as Array<any>).map(GetRegulatedEntityById200ResponseAttributesInnerToJSON)),
        'entity_post_code': value['entityPostCode'],
        'entity_name': value['entityName'],
        'entity_town_city': value['entityTownCity'],
        'entity_address': value['entityAddress'],
        'certificate_authority_ca_owner_id': value['certificateAuthorityCaOwnerId'],
    };
}

