/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetBankLevelDynamicResourceDoc200Response } from './GetBankLevelDynamicResourceDoc200Response';
import {
    GetBankLevelDynamicResourceDoc200ResponseFromJSON,
    GetBankLevelDynamicResourceDoc200ResponseFromJSONTyped,
    GetBankLevelDynamicResourceDoc200ResponseToJSON,
    GetBankLevelDynamicResourceDoc200ResponseToJSONTyped,
} from './GetBankLevelDynamicResourceDoc200Response';

/**
 * 
 * @export
 * @interface GetAllDynamicResourceDocs200Response
 */
export interface GetAllDynamicResourceDocs200Response {
    /**
     * 
     * @type {Array<GetBankLevelDynamicResourceDoc200Response>}
     * @memberof GetAllDynamicResourceDocs200Response
     */
    dynamicResourceDocs?: Array<GetBankLevelDynamicResourceDoc200Response>;
}

/**
 * Check if a given object implements the GetAllDynamicResourceDocs200Response interface.
 */
export function instanceOfGetAllDynamicResourceDocs200Response(value: object): value is GetAllDynamicResourceDocs200Response {
    return true;
}

export function GetAllDynamicResourceDocs200ResponseFromJSON(json: any): GetAllDynamicResourceDocs200Response {
    return GetAllDynamicResourceDocs200ResponseFromJSONTyped(json, false);
}

export function GetAllDynamicResourceDocs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllDynamicResourceDocs200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'dynamicResourceDocs': json['dynamic-resource-docs'] == null ? undefined : ((json['dynamic-resource-docs'] as Array<any>).map(GetBankLevelDynamicResourceDoc200ResponseFromJSON)),
    };
}

export function GetAllDynamicResourceDocs200ResponseToJSON(json: any): GetAllDynamicResourceDocs200Response {
    return GetAllDynamicResourceDocs200ResponseToJSONTyped(json, false);
}

export function GetAllDynamicResourceDocs200ResponseToJSONTyped(value?: GetAllDynamicResourceDocs200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dynamic-resource-docs': value['dynamicResourceDocs'] == null ? undefined : ((value['dynamicResourceDocs'] as Array<any>).map(GetBankLevelDynamicResourceDoc200ResponseToJSON)),
    };
}

