/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetCardsForBank200ResponseCardsInnerAccountViewsAvailableInner } from './GetCardsForBank200ResponseCardsInnerAccountViewsAvailableInner';
import {
    GetCardsForBank200ResponseCardsInnerAccountViewsAvailableInnerFromJSON,
    GetCardsForBank200ResponseCardsInnerAccountViewsAvailableInnerFromJSONTyped,
    GetCardsForBank200ResponseCardsInnerAccountViewsAvailableInnerToJSON,
    GetCardsForBank200ResponseCardsInnerAccountViewsAvailableInnerToJSONTyped,
} from './GetCardsForBank200ResponseCardsInnerAccountViewsAvailableInner';

/**
 * 
 * @export
 * @interface GetCardsForBank200ResponseCardsInnerAccount
 */
export interface GetCardsForBank200ResponseCardsInnerAccount {
    /**
     * 
     * @type {string}
     * @memberof GetCardsForBank200ResponseCardsInnerAccount
     */
    bankId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCardsForBank200ResponseCardsInnerAccount
     */
    label?: string;
    /**
     * 
     * @type {Array<GetCardsForBank200ResponseCardsInnerAccountViewsAvailableInner>}
     * @memberof GetCardsForBank200ResponseCardsInnerAccount
     */
    viewsAvailable?: Array<GetCardsForBank200ResponseCardsInnerAccountViewsAvailableInner>;
    /**
     * 
     * @type {string}
     * @memberof GetCardsForBank200ResponseCardsInnerAccount
     */
    id?: string;
}

/**
 * Check if a given object implements the GetCardsForBank200ResponseCardsInnerAccount interface.
 */
export function instanceOfGetCardsForBank200ResponseCardsInnerAccount(value: object): value is GetCardsForBank200ResponseCardsInnerAccount {
    return true;
}

export function GetCardsForBank200ResponseCardsInnerAccountFromJSON(json: any): GetCardsForBank200ResponseCardsInnerAccount {
    return GetCardsForBank200ResponseCardsInnerAccountFromJSONTyped(json, false);
}

export function GetCardsForBank200ResponseCardsInnerAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCardsForBank200ResponseCardsInnerAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'bankId': json['bank_id'] == null ? undefined : json['bank_id'],
        'label': json['label'] == null ? undefined : json['label'],
        'viewsAvailable': json['views_available'] == null ? undefined : ((json['views_available'] as Array<any>).map(GetCardsForBank200ResponseCardsInnerAccountViewsAvailableInnerFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function GetCardsForBank200ResponseCardsInnerAccountToJSON(json: any): GetCardsForBank200ResponseCardsInnerAccount {
    return GetCardsForBank200ResponseCardsInnerAccountToJSONTyped(json, false);
}

export function GetCardsForBank200ResponseCardsInnerAccountToJSONTyped(value?: GetCardsForBank200ResponseCardsInnerAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bank_id': value['bankId'],
        'label': value['label'],
        'views_available': value['viewsAvailable'] == null ? undefined : ((value['viewsAvailable'] as Array<any>).map(GetCardsForBank200ResponseCardsInnerAccountViewsAvailableInnerToJSON)),
        'id': value['id'],
    };
}

