/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetMeeting200ResponsePresent } from './GetMeeting200ResponsePresent';
import {
    GetMeeting200ResponsePresentFromJSON,
    GetMeeting200ResponsePresentFromJSONTyped,
    GetMeeting200ResponsePresentToJSON,
    GetMeeting200ResponsePresentToJSONTyped,
} from './GetMeeting200ResponsePresent';
import type { GetMeeting200ResponseInviteesInner } from './GetMeeting200ResponseInviteesInner';
import {
    GetMeeting200ResponseInviteesInnerFromJSON,
    GetMeeting200ResponseInviteesInnerFromJSONTyped,
    GetMeeting200ResponseInviteesInnerToJSON,
    GetMeeting200ResponseInviteesInnerToJSONTyped,
} from './GetMeeting200ResponseInviteesInner';
import type { GetMeeting200ResponseKeys } from './GetMeeting200ResponseKeys';
import {
    GetMeeting200ResponseKeysFromJSON,
    GetMeeting200ResponseKeysFromJSONTyped,
    GetMeeting200ResponseKeysToJSON,
    GetMeeting200ResponseKeysToJSONTyped,
} from './GetMeeting200ResponseKeys';
import type { GetMeeting200ResponseCreator } from './GetMeeting200ResponseCreator';
import {
    GetMeeting200ResponseCreatorFromJSON,
    GetMeeting200ResponseCreatorFromJSONTyped,
    GetMeeting200ResponseCreatorToJSON,
    GetMeeting200ResponseCreatorToJSONTyped,
} from './GetMeeting200ResponseCreator';

/**
 * 
 * @export
 * @interface GetMeeting200Response
 */
export interface GetMeeting200Response {
    /**
     * 
     * @type {GetMeeting200ResponsePresent}
     * @memberof GetMeeting200Response
     */
    present?: GetMeeting200ResponsePresent;
    /**
     * 
     * @type {string}
     * @memberof GetMeeting200Response
     */
    providerId?: string;
    /**
     * 
     * @type {GetMeeting200ResponseCreator}
     * @memberof GetMeeting200Response
     */
    creator?: GetMeeting200ResponseCreator;
    /**
     * 
     * @type {Array<GetMeeting200ResponseInviteesInner>}
     * @memberof GetMeeting200Response
     */
    invitees?: Array<GetMeeting200ResponseInviteesInner>;
    /**
     * 
     * @type {string}
     * @memberof GetMeeting200Response
     */
    bankId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMeeting200Response
     */
    purposeId?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetMeeting200Response
     */
    when?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetMeeting200Response
     */
    meetingId?: string;
    /**
     * 
     * @type {GetMeeting200ResponseKeys}
     * @memberof GetMeeting200Response
     */
    keys?: GetMeeting200ResponseKeys;
}

/**
 * Check if a given object implements the GetMeeting200Response interface.
 */
export function instanceOfGetMeeting200Response(value: object): value is GetMeeting200Response {
    return true;
}

export function GetMeeting200ResponseFromJSON(json: any): GetMeeting200Response {
    return GetMeeting200ResponseFromJSONTyped(json, false);
}

export function GetMeeting200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMeeting200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'present': json['present'] == null ? undefined : GetMeeting200ResponsePresentFromJSON(json['present']),
        'providerId': json['provider_id'] == null ? undefined : json['provider_id'],
        'creator': json['creator'] == null ? undefined : GetMeeting200ResponseCreatorFromJSON(json['creator']),
        'invitees': json['invitees'] == null ? undefined : ((json['invitees'] as Array<any>).map(GetMeeting200ResponseInviteesInnerFromJSON)),
        'bankId': json['bank_id'] == null ? undefined : json['bank_id'],
        'purposeId': json['purpose_id'] == null ? undefined : json['purpose_id'],
        'when': json['when'] == null ? undefined : (new Date(json['when'])),
        'meetingId': json['meeting_id'] == null ? undefined : json['meeting_id'],
        'keys': json['keys'] == null ? undefined : GetMeeting200ResponseKeysFromJSON(json['keys']),
    };
}

export function GetMeeting200ResponseToJSON(json: any): GetMeeting200Response {
    return GetMeeting200ResponseToJSONTyped(json, false);
}

export function GetMeeting200ResponseToJSONTyped(value?: GetMeeting200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'present': GetMeeting200ResponsePresentToJSON(value['present']),
        'provider_id': value['providerId'],
        'creator': GetMeeting200ResponseCreatorToJSON(value['creator']),
        'invitees': value['invitees'] == null ? undefined : ((value['invitees'] as Array<any>).map(GetMeeting200ResponseInviteesInnerToJSON)),
        'bank_id': value['bankId'],
        'purpose_id': value['purposeId'],
        'when': value['when'] == null ? value['when'] : value['when'].toISOString(),
        'meeting_id': value['meetingId'],
        'keys': GetMeeting200ResponseKeysToJSON(value['keys']),
    };
}

