/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetMyCustomersAtBank200ResponseCustomersInnerCreditLimit } from './GetMyCustomersAtBank200ResponseCustomersInnerCreditLimit';
import {
    GetMyCustomersAtBank200ResponseCustomersInnerCreditLimitFromJSON,
    GetMyCustomersAtBank200ResponseCustomersInnerCreditLimitFromJSONTyped,
    GetMyCustomersAtBank200ResponseCustomersInnerCreditLimitToJSON,
    GetMyCustomersAtBank200ResponseCustomersInnerCreditLimitToJSONTyped,
} from './GetMyCustomersAtBank200ResponseCustomersInnerCreditLimit';
import type { GetMyCustomersAtBank200ResponseCustomersInnerCreditRating } from './GetMyCustomersAtBank200ResponseCustomersInnerCreditRating';
import {
    GetMyCustomersAtBank200ResponseCustomersInnerCreditRatingFromJSON,
    GetMyCustomersAtBank200ResponseCustomersInnerCreditRatingFromJSONTyped,
    GetMyCustomersAtBank200ResponseCustomersInnerCreditRatingToJSON,
    GetMyCustomersAtBank200ResponseCustomersInnerCreditRatingToJSONTyped,
} from './GetMyCustomersAtBank200ResponseCustomersInnerCreditRating';
import type { GetMyCustomersAtBank200ResponseCustomersInnerFaceImage } from './GetMyCustomersAtBank200ResponseCustomersInnerFaceImage';
import {
    GetMyCustomersAtBank200ResponseCustomersInnerFaceImageFromJSON,
    GetMyCustomersAtBank200ResponseCustomersInnerFaceImageFromJSONTyped,
    GetMyCustomersAtBank200ResponseCustomersInnerFaceImageToJSON,
    GetMyCustomersAtBank200ResponseCustomersInnerFaceImageToJSONTyped,
} from './GetMyCustomersAtBank200ResponseCustomersInnerFaceImage';

/**
 * 
 * @export
 * @interface GetMyCustomersAtBank200ResponseCustomersInner
 */
export interface GetMyCustomersAtBank200ResponseCustomersInner {
    /**
     * 
     * @type {string}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    customerId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    mobilePhoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    customerNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    highestEducationAttained?: string;
    /**
     * 
     * @type {Array<Date>}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    dobOfDependants?: Array<Date>;
    /**
     * 
     * @type {string}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    bankId?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    dateOfBirth?: Date;
    /**
     * 
     * @type {GetMyCustomersAtBank200ResponseCustomersInnerCreditRating}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    creditRating?: GetMyCustomersAtBank200ResponseCustomersInnerCreditRating;
    /**
     * 
     * @type {Date}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    lastOkDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    employmentStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    legalName?: string;
    /**
     * 
     * @type {GetMyCustomersAtBank200ResponseCustomersInnerCreditLimit}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    creditLimit?: GetMyCustomersAtBank200ResponseCustomersInnerCreditLimit;
    /**
     * 
     * @type {GetMyCustomersAtBank200ResponseCustomersInnerFaceImage}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    faceImage?: GetMyCustomersAtBank200ResponseCustomersInnerFaceImage;
    /**
     * 
     * @type {number}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    dependants?: number;
    /**
     * 
     * @type {string}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    relationshipStatus?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetMyCustomersAtBank200ResponseCustomersInner
     */
    kycStatus?: boolean;
}

/**
 * Check if a given object implements the GetMyCustomersAtBank200ResponseCustomersInner interface.
 */
export function instanceOfGetMyCustomersAtBank200ResponseCustomersInner(value: object): value is GetMyCustomersAtBank200ResponseCustomersInner {
    return true;
}

export function GetMyCustomersAtBank200ResponseCustomersInnerFromJSON(json: any): GetMyCustomersAtBank200ResponseCustomersInner {
    return GetMyCustomersAtBank200ResponseCustomersInnerFromJSONTyped(json, false);
}

export function GetMyCustomersAtBank200ResponseCustomersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMyCustomersAtBank200ResponseCustomersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'customerId': json['customer_id'] == null ? undefined : json['customer_id'],
        'email': json['email'] == null ? undefined : json['email'],
        'mobilePhoneNumber': json['mobile_phone_number'] == null ? undefined : json['mobile_phone_number'],
        'customerNumber': json['customer_number'] == null ? undefined : json['customer_number'],
        'highestEducationAttained': json['highest_education_attained'] == null ? undefined : json['highest_education_attained'],
        'dobOfDependants': json['dob_of_dependants'] == null ? undefined : json['dob_of_dependants'],
        'bankId': json['bank_id'] == null ? undefined : json['bank_id'],
        'dateOfBirth': json['date_of_birth'] == null ? undefined : (new Date(json['date_of_birth'])),
        'creditRating': json['credit_rating'] == null ? undefined : GetMyCustomersAtBank200ResponseCustomersInnerCreditRatingFromJSON(json['credit_rating']),
        'lastOkDate': json['last_ok_date'] == null ? undefined : (new Date(json['last_ok_date'])),
        'employmentStatus': json['employment_status'] == null ? undefined : json['employment_status'],
        'legalName': json['legal_name'] == null ? undefined : json['legal_name'],
        'creditLimit': json['credit_limit'] == null ? undefined : GetMyCustomersAtBank200ResponseCustomersInnerCreditLimitFromJSON(json['credit_limit']),
        'faceImage': json['face_image'] == null ? undefined : GetMyCustomersAtBank200ResponseCustomersInnerFaceImageFromJSON(json['face_image']),
        'dependants': json['dependants'] == null ? undefined : json['dependants'],
        'relationshipStatus': json['relationship_status'] == null ? undefined : json['relationship_status'],
        'kycStatus': json['kyc_status'] == null ? undefined : json['kyc_status'],
    };
}

export function GetMyCustomersAtBank200ResponseCustomersInnerToJSON(json: any): GetMyCustomersAtBank200ResponseCustomersInner {
    return GetMyCustomersAtBank200ResponseCustomersInnerToJSONTyped(json, false);
}

export function GetMyCustomersAtBank200ResponseCustomersInnerToJSONTyped(value?: GetMyCustomersAtBank200ResponseCustomersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customer_id': value['customerId'],
        'email': value['email'],
        'mobile_phone_number': value['mobilePhoneNumber'],
        'customer_number': value['customerNumber'],
        'highest_education_attained': value['highestEducationAttained'],
        'dob_of_dependants': value['dobOfDependants'],
        'bank_id': value['bankId'],
        'date_of_birth': value['dateOfBirth'] == null ? value['dateOfBirth'] : value['dateOfBirth'].toISOString(),
        'credit_rating': GetMyCustomersAtBank200ResponseCustomersInnerCreditRatingToJSON(value['creditRating']),
        'last_ok_date': value['lastOkDate'] == null ? value['lastOkDate'] : value['lastOkDate'].toISOString(),
        'employment_status': value['employmentStatus'],
        'legal_name': value['legalName'],
        'credit_limit': GetMyCustomersAtBank200ResponseCustomersInnerCreditLimitToJSON(value['creditLimit']),
        'face_image': GetMyCustomersAtBank200ResponseCustomersInnerFaceImageToJSON(value['faceImage']),
        'dependants': value['dependants'],
        'relationship_status': value['relationshipStatus'],
        'kyc_status': value['kycStatus'],
    };
}

