/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetProduct200ResponseAttributesInner } from './GetProduct200ResponseAttributesInner';
import {
    GetProduct200ResponseAttributesInnerFromJSON,
    GetProduct200ResponseAttributesInnerFromJSONTyped,
    GetProduct200ResponseAttributesInnerToJSON,
    GetProduct200ResponseAttributesInnerToJSONTyped,
} from './GetProduct200ResponseAttributesInner';
import type { GetProductTree200ResponseParentProductParentProductMeta } from './GetProductTree200ResponseParentProductParentProductMeta';
import {
    GetProductTree200ResponseParentProductParentProductMetaFromJSON,
    GetProductTree200ResponseParentProductParentProductMetaFromJSONTyped,
    GetProductTree200ResponseParentProductParentProductMetaToJSON,
    GetProductTree200ResponseParentProductParentProductMetaToJSONTyped,
} from './GetProductTree200ResponseParentProductParentProductMeta';
import type { GetProduct200ResponseFeesInner } from './GetProduct200ResponseFeesInner';
import {
    GetProduct200ResponseFeesInnerFromJSON,
    GetProduct200ResponseFeesInnerFromJSONTyped,
    GetProduct200ResponseFeesInnerToJSON,
    GetProduct200ResponseFeesInnerToJSONTyped,
} from './GetProduct200ResponseFeesInner';

/**
 * 
 * @export
 * @interface GetProduct200Response
 */
export interface GetProduct200Response {
    /**
     * 
     * @type {string}
     * @memberof GetProduct200Response
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProduct200Response
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProduct200Response
     */
    termsAndConditionsUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProduct200Response
     */
    moreInfoUrl?: string;
    /**
     * 
     * @type {Array<GetProduct200ResponseAttributesInner>}
     * @memberof GetProduct200Response
     */
    attributes?: Array<GetProduct200ResponseAttributesInner>;
    /**
     * 
     * @type {string}
     * @memberof GetProduct200Response
     */
    productCode?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProduct200Response
     */
    bankId?: string;
    /**
     * 
     * @type {GetProductTree200ResponseParentProductParentProductMeta}
     * @memberof GetProduct200Response
     */
    meta?: GetProductTree200ResponseParentProductParentProductMeta;
    /**
     * 
     * @type {Array<GetProduct200ResponseFeesInner>}
     * @memberof GetProduct200Response
     */
    fees?: Array<GetProduct200ResponseFeesInner>;
    /**
     * 
     * @type {string}
     * @memberof GetProduct200Response
     */
    parentProductCode?: string;
}

/**
 * Check if a given object implements the GetProduct200Response interface.
 */
export function instanceOfGetProduct200Response(value: object): value is GetProduct200Response {
    return true;
}

export function GetProduct200ResponseFromJSON(json: any): GetProduct200Response {
    return GetProduct200ResponseFromJSONTyped(json, false);
}

export function GetProduct200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProduct200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'termsAndConditionsUrl': json['terms_and_conditions_url'] == null ? undefined : json['terms_and_conditions_url'],
        'moreInfoUrl': json['more_info_url'] == null ? undefined : json['more_info_url'],
        'attributes': json['attributes'] == null ? undefined : ((json['attributes'] as Array<any>).map(GetProduct200ResponseAttributesInnerFromJSON)),
        'productCode': json['product_code'] == null ? undefined : json['product_code'],
        'bankId': json['bank_id'] == null ? undefined : json['bank_id'],
        'meta': json['meta'] == null ? undefined : GetProductTree200ResponseParentProductParentProductMetaFromJSON(json['meta']),
        'fees': json['fees'] == null ? undefined : ((json['fees'] as Array<any>).map(GetProduct200ResponseFeesInnerFromJSON)),
        'parentProductCode': json['parent_product_code'] == null ? undefined : json['parent_product_code'],
    };
}

export function GetProduct200ResponseToJSON(json: any): GetProduct200Response {
    return GetProduct200ResponseToJSONTyped(json, false);
}

export function GetProduct200ResponseToJSONTyped(value?: GetProduct200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'terms_and_conditions_url': value['termsAndConditionsUrl'],
        'more_info_url': value['moreInfoUrl'],
        'attributes': value['attributes'] == null ? undefined : ((value['attributes'] as Array<any>).map(GetProduct200ResponseAttributesInnerToJSON)),
        'product_code': value['productCode'],
        'bank_id': value['bankId'],
        'meta': GetProductTree200ResponseParentProductParentProductMetaToJSON(value['meta']),
        'fees': value['fees'] == null ? undefined : ((value['fees'] as Array<any>).map(GetProduct200ResponseFeesInnerToJSON)),
        'parent_product_code': value['parentProductCode'],
    };
}

