/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetSystemViewsIds200ResponseViewsInner } from './GetSystemViewsIds200ResponseViewsInner';
import {
    GetSystemViewsIds200ResponseViewsInnerFromJSON,
    GetSystemViewsIds200ResponseViewsInnerFromJSONTyped,
    GetSystemViewsIds200ResponseViewsInnerToJSON,
    GetSystemViewsIds200ResponseViewsInnerToJSONTyped,
} from './GetSystemViewsIds200ResponseViewsInner';

/**
 * 
 * @export
 * @interface GetPrivateAccountIdsbyBankId200Response
 */
export interface GetPrivateAccountIdsbyBankId200Response {
    /**
     * 
     * @type {Array<GetSystemViewsIds200ResponseViewsInner>}
     * @memberof GetPrivateAccountIdsbyBankId200Response
     */
    accounts?: Array<GetSystemViewsIds200ResponseViewsInner>;
}

/**
 * Check if a given object implements the GetPrivateAccountIdsbyBankId200Response interface.
 */
export function instanceOfGetPrivateAccountIdsbyBankId200Response(value: object): value is GetPrivateAccountIdsbyBankId200Response {
    return true;
}

export function GetPrivateAccountIdsbyBankId200ResponseFromJSON(json: any): GetPrivateAccountIdsbyBankId200Response {
    return GetPrivateAccountIdsbyBankId200ResponseFromJSONTyped(json, false);
}

export function GetPrivateAccountIdsbyBankId200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPrivateAccountIdsbyBankId200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accounts': json['accounts'] == null ? undefined : ((json['accounts'] as Array<any>).map(GetSystemViewsIds200ResponseViewsInnerFromJSON)),
    };
}

export function GetPrivateAccountIdsbyBankId200ResponseToJSON(json: any): GetPrivateAccountIdsbyBankId200Response {
    return GetPrivateAccountIdsbyBankId200ResponseToJSONTyped(json, false);
}

export function GetPrivateAccountIdsbyBankId200ResponseToJSONTyped(value?: GetPrivateAccountIdsbyBankId200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accounts': value['accounts'] == null ? undefined : ((value['accounts'] as Array<any>).map(GetSystemViewsIds200ResponseViewsInnerToJSON)),
    };
}

