/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUsersWithAccountAccess200ResponseUsersInner
 */
export interface GetUsersWithAccountAccess200ResponseUsersInner {
    /**
     * 
     * @type {string}
     * @memberof GetUsersWithAccountAccess200ResponseUsersInner
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUsersWithAccountAccess200ResponseUsersInner
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUsersWithAccountAccess200ResponseUsersInner
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUsersWithAccountAccess200ResponseUsersInner
     */
    accessSource?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUsersWithAccountAccess200ResponseUsersInner
     */
    userId?: string;
}

/**
 * Check if a given object implements the GetUsersWithAccountAccess200ResponseUsersInner interface.
 */
export function instanceOfGetUsersWithAccountAccess200ResponseUsersInner(value: object): value is GetUsersWithAccountAccess200ResponseUsersInner {
    return true;
}

export function GetUsersWithAccountAccess200ResponseUsersInnerFromJSON(json: any): GetUsersWithAccountAccess200ResponseUsersInner {
    return GetUsersWithAccountAccess200ResponseUsersInnerFromJSONTyped(json, false);
}

export function GetUsersWithAccountAccess200ResponseUsersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUsersWithAccountAccess200ResponseUsersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'] == null ? undefined : json['provider'],
        'email': json['email'] == null ? undefined : json['email'],
        'username': json['username'] == null ? undefined : json['username'],
        'accessSource': json['access_source'] == null ? undefined : json['access_source'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function GetUsersWithAccountAccess200ResponseUsersInnerToJSON(json: any): GetUsersWithAccountAccess200ResponseUsersInner {
    return GetUsersWithAccountAccess200ResponseUsersInnerToJSONTyped(json, false);
}

export function GetUsersWithAccountAccess200ResponseUsersInnerToJSONTyped(value?: GetUsersWithAccountAccess200ResponseUsersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'email': value['email'],
        'username': value['username'],
        'access_source': value['accessSource'],
        'user_id': value['userId'],
    };
}

