/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateTransactionRequestCounterparty200ResponseDetailsToSepaCreditTransfersDebtorAccount } from './CreateTransactionRequestCounterparty200ResponseDetailsToSepaCreditTransfersDebtorAccount';
import {
    CreateTransactionRequestCounterparty200ResponseDetailsToSepaCreditTransfersDebtorAccountFromJSON,
    CreateTransactionRequestCounterparty200ResponseDetailsToSepaCreditTransfersDebtorAccountFromJSONTyped,
    CreateTransactionRequestCounterparty200ResponseDetailsToSepaCreditTransfersDebtorAccountToJSON,
    CreateTransactionRequestCounterparty200ResponseDetailsToSepaCreditTransfersDebtorAccountToJSONTyped,
} from './CreateTransactionRequestCounterparty200ResponseDetailsToSepaCreditTransfersDebtorAccount';

/**
 * 
 * @export
 * @interface UpdateConsentAccountAccessByConsentIdRequestAccess
 */
export interface UpdateConsentAccountAccessByConsentIdRequestAccess {
    /**
     * 
     * @type {Array<CreateTransactionRequestCounterparty200ResponseDetailsToSepaCreditTransfersDebtorAccount>}
     * @memberof UpdateConsentAccountAccessByConsentIdRequestAccess
     */
    accounts?: Array<CreateTransactionRequestCounterparty200ResponseDetailsToSepaCreditTransfersDebtorAccount>;
}

/**
 * Check if a given object implements the UpdateConsentAccountAccessByConsentIdRequestAccess interface.
 */
export function instanceOfUpdateConsentAccountAccessByConsentIdRequestAccess(value: object): value is UpdateConsentAccountAccessByConsentIdRequestAccess {
    return true;
}

export function UpdateConsentAccountAccessByConsentIdRequestAccessFromJSON(json: any): UpdateConsentAccountAccessByConsentIdRequestAccess {
    return UpdateConsentAccountAccessByConsentIdRequestAccessFromJSONTyped(json, false);
}

export function UpdateConsentAccountAccessByConsentIdRequestAccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateConsentAccountAccessByConsentIdRequestAccess {
    if (json == null) {
        return json;
    }
    return {
        
        'accounts': json['accounts'] == null ? undefined : ((json['accounts'] as Array<any>).map(CreateTransactionRequestCounterparty200ResponseDetailsToSepaCreditTransfersDebtorAccountFromJSON)),
    };
}

export function UpdateConsentAccountAccessByConsentIdRequestAccessToJSON(json: any): UpdateConsentAccountAccessByConsentIdRequestAccess {
    return UpdateConsentAccountAccessByConsentIdRequestAccessToJSONTyped(json, false);
}

export function UpdateConsentAccountAccessByConsentIdRequestAccessToJSONTyped(value?: UpdateConsentAccountAccessByConsentIdRequestAccess | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accounts': value['accounts'] == null ? undefined : ((value['accounts'] as Array<any>).map(CreateTransactionRequestCounterparty200ResponseDetailsToSepaCreditTransfersDebtorAccountToJSON)),
    };
}

