/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidateAbacRule200Response
 */
export interface ValidateAbacRule200Response {
    /**
     * 
     * @type {string}
     * @memberof ValidateAbacRule200Response
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ValidateAbacRule200Response
     */
    valid?: boolean;
}

/**
 * Check if a given object implements the ValidateAbacRule200Response interface.
 */
export function instanceOfValidateAbacRule200Response(value: object): value is ValidateAbacRule200Response {
    return true;
}

export function ValidateAbacRule200ResponseFromJSON(json: any): ValidateAbacRule200Response {
    return ValidateAbacRule200ResponseFromJSONTyped(json, false);
}

export function ValidateAbacRule200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateAbacRule200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'valid': json['valid'] == null ? undefined : json['valid'],
    };
}

export function ValidateAbacRule200ResponseToJSON(json: any): ValidateAbacRule200Response {
    return ValidateAbacRule200ResponseToJSONTyped(json, false);
}

export function ValidateAbacRule200ResponseToJSONTyped(value?: ValidateAbacRule200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'valid': value['valid'],
    };
}

