/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.openbankproject.model


case class GetBranches200ResponseBranchesInnerAddress(
  city: Option[String] = None,
  line2: Option[String] = None,
  state: Option[String] = None,
  postcode: Option[String] = None,
  county: Option[String] = None,
  countryCode: Option[String] = None,
  line3: Option[String] = None,
  line1: Option[String] = None
)

