/*
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateGroupRequest {
    #[serde(rename = "list_of_roles", skip_serializing_if = "Option::is_none")]
    pub list_of_roles: Option<Vec<String>>,
    #[serde(rename = "bank_id", skip_serializing_if = "Option::is_none")]
    pub bank_id: Option<String>,
    #[serde(rename = "group_name", skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
    #[serde(rename = "is_enabled", skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<bool>,
    #[serde(rename = "group_description", skip_serializing_if = "Option::is_none")]
    pub group_description: Option<String>,
}

impl CreateGroupRequest {
    pub fn new() -> CreateGroupRequest {
        CreateGroupRequest {
            list_of_roles: None,
            bank_id: None,
            group_name: None,
            is_enabled: None,
            group_description: None,
        }
    }
}

