/*
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAccount200Response {
    #[serde(rename = "branch_id", skip_serializing_if = "Option::is_none")]
    pub branch_id: Option<String>,
    #[serde(rename = "account_routings", skip_serializing_if = "Option::is_none")]
    pub account_routings: Option<Vec<models::GetCheckbookOrders200ResponseAccountAccountRoutingsInner>>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "bank_id", skip_serializing_if = "Option::is_none")]
    pub bank_id: Option<String>,
    #[serde(rename = "account_id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl UpdateAccount200Response {
    pub fn new() -> UpdateAccount200Response {
        UpdateAccount200Response {
            branch_id: None,
            account_routings: None,
            label: None,
            bank_id: None,
            account_id: None,
            r#type: None,
        }
    }
}

