<?php
/**
 * GetExplicitCounterpartyById200ResponseMetadata
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenBankProject
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenBankProject\Model;

use \ArrayAccess;
use \OpenBankProject\ObjectSerializer;

/**
 * GetExplicitCounterpartyById200ResponseMetadata Class Doc Comment
 *
 * @category Class
 * @package  OpenBankProject
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetExplicitCounterpartyById200ResponseMetadata implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'getExplicitCounterpartyById_200_response_metadata';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'public_alias' => 'string',
        'physical_location' => '\OpenBankProject\Model\GetExplicitCounterpartyById200ResponseMetadataPhysicalLocation',
        'image_url' => 'string',
        'private_alias' => 'string',
        'url' => 'string',
        'more_info' => 'string',
        'corporate_location' => '\OpenBankProject\Model\GetExplicitCounterpartyById200ResponseMetadataPhysicalLocation',
        'open_corporates_url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'public_alias' => null,
        'physical_location' => null,
        'image_url' => null,
        'private_alias' => null,
        'url' => null,
        'more_info' => null,
        'corporate_location' => null,
        'open_corporates_url' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'public_alias' => false,
        'physical_location' => false,
        'image_url' => false,
        'private_alias' => false,
        'url' => false,
        'more_info' => false,
        'corporate_location' => false,
        'open_corporates_url' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'public_alias' => 'public_alias',
        'physical_location' => 'physical_location',
        'image_url' => 'image_url',
        'private_alias' => 'private_alias',
        'url' => 'url',
        'more_info' => 'more_info',
        'corporate_location' => 'corporate_location',
        'open_corporates_url' => 'open_corporates_url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'public_alias' => 'setPublicAlias',
        'physical_location' => 'setPhysicalLocation',
        'image_url' => 'setImageUrl',
        'private_alias' => 'setPrivateAlias',
        'url' => 'setUrl',
        'more_info' => 'setMoreInfo',
        'corporate_location' => 'setCorporateLocation',
        'open_corporates_url' => 'setOpenCorporatesUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'public_alias' => 'getPublicAlias',
        'physical_location' => 'getPhysicalLocation',
        'image_url' => 'getImageUrl',
        'private_alias' => 'getPrivateAlias',
        'url' => 'getUrl',
        'more_info' => 'getMoreInfo',
        'corporate_location' => 'getCorporateLocation',
        'open_corporates_url' => 'getOpenCorporatesUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('public_alias', $data ?? [], null);
        $this->setIfExists('physical_location', $data ?? [], null);
        $this->setIfExists('image_url', $data ?? [], null);
        $this->setIfExists('private_alias', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('more_info', $data ?? [], null);
        $this->setIfExists('corporate_location', $data ?? [], null);
        $this->setIfExists('open_corporates_url', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets public_alias
     *
     * @return string|null
     */
    public function getPublicAlias()
    {
        return $this->container['public_alias'];
    }

    /**
     * Sets public_alias
     *
     * @param string|null $public_alias public_alias
     *
     * @return self
     */
    public function setPublicAlias($public_alias)
    {
        if (is_null($public_alias)) {
            throw new \InvalidArgumentException('non-nullable public_alias cannot be null');
        }
        $this->container['public_alias'] = $public_alias;

        return $this;
    }

    /**
     * Gets physical_location
     *
     * @return \OpenBankProject\Model\GetExplicitCounterpartyById200ResponseMetadataPhysicalLocation|null
     */
    public function getPhysicalLocation()
    {
        return $this->container['physical_location'];
    }

    /**
     * Sets physical_location
     *
     * @param \OpenBankProject\Model\GetExplicitCounterpartyById200ResponseMetadataPhysicalLocation|null $physical_location physical_location
     *
     * @return self
     */
    public function setPhysicalLocation($physical_location)
    {
        if (is_null($physical_location)) {
            throw new \InvalidArgumentException('non-nullable physical_location cannot be null');
        }
        $this->container['physical_location'] = $physical_location;

        return $this;
    }

    /**
     * Gets image_url
     *
     * @return string|null
     */
    public function getImageUrl()
    {
        return $this->container['image_url'];
    }

    /**
     * Sets image_url
     *
     * @param string|null $image_url image_url
     *
     * @return self
     */
    public function setImageUrl($image_url)
    {
        if (is_null($image_url)) {
            throw new \InvalidArgumentException('non-nullable image_url cannot be null');
        }
        $this->container['image_url'] = $image_url;

        return $this;
    }

    /**
     * Gets private_alias
     *
     * @return string|null
     */
    public function getPrivateAlias()
    {
        return $this->container['private_alias'];
    }

    /**
     * Sets private_alias
     *
     * @param string|null $private_alias private_alias
     *
     * @return self
     */
    public function setPrivateAlias($private_alias)
    {
        if (is_null($private_alias)) {
            throw new \InvalidArgumentException('non-nullable private_alias cannot be null');
        }
        $this->container['private_alias'] = $private_alias;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets more_info
     *
     * @return string|null
     */
    public function getMoreInfo()
    {
        return $this->container['more_info'];
    }

    /**
     * Sets more_info
     *
     * @param string|null $more_info more_info
     *
     * @return self
     */
    public function setMoreInfo($more_info)
    {
        if (is_null($more_info)) {
            throw new \InvalidArgumentException('non-nullable more_info cannot be null');
        }
        $this->container['more_info'] = $more_info;

        return $this;
    }

    /**
     * Gets corporate_location
     *
     * @return \OpenBankProject\Model\GetExplicitCounterpartyById200ResponseMetadataPhysicalLocation|null
     */
    public function getCorporateLocation()
    {
        return $this->container['corporate_location'];
    }

    /**
     * Sets corporate_location
     *
     * @param \OpenBankProject\Model\GetExplicitCounterpartyById200ResponseMetadataPhysicalLocation|null $corporate_location corporate_location
     *
     * @return self
     */
    public function setCorporateLocation($corporate_location)
    {
        if (is_null($corporate_location)) {
            throw new \InvalidArgumentException('non-nullable corporate_location cannot be null');
        }
        $this->container['corporate_location'] = $corporate_location;

        return $this;
    }

    /**
     * Gets open_corporates_url
     *
     * @return string|null
     */
    public function getOpenCorporatesUrl()
    {
        return $this->container['open_corporates_url'];
    }

    /**
     * Sets open_corporates_url
     *
     * @param string|null $open_corporates_url open_corporates_url
     *
     * @return self
     */
    public function setOpenCorporatesUrl($open_corporates_url)
    {
        if (is_null($open_corporates_url)) {
            throw new \InvalidArgumentException('non-nullable open_corporates_url cannot be null');
        }
        $this->container['open_corporates_url'] = $open_corporates_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


