/* tslint:disable */
/* eslint-disable */
/**
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateOrUpdateTransactionRequestAttributeDefinitionRequest,
  CreatePersonalDataFieldRequest,
  GetCoreTransactionsForBankAccount200ResponseTransactionsInnerTransactionAttributesInner,
  GetTransactionAttributes200Response,
  GetTransactionRequestAttributeDefinition200Response,
  GetTransactionRequestAttributeDefinition200ResponseAttributesInner,
} from '../models/index';
import {
    CreateOrUpdateTransactionRequestAttributeDefinitionRequestFromJSON,
    CreateOrUpdateTransactionRequestAttributeDefinitionRequestToJSON,
    CreatePersonalDataFieldRequestFromJSON,
    CreatePersonalDataFieldRequestToJSON,
    GetCoreTransactionsForBankAccount200ResponseTransactionsInnerTransactionAttributesInnerFromJSON,
    GetCoreTransactionsForBankAccount200ResponseTransactionsInnerTransactionAttributesInnerToJSON,
    GetTransactionAttributes200ResponseFromJSON,
    GetTransactionAttributes200ResponseToJSON,
    GetTransactionRequestAttributeDefinition200ResponseFromJSON,
    GetTransactionRequestAttributeDefinition200ResponseToJSON,
    GetTransactionRequestAttributeDefinition200ResponseAttributesInnerFromJSON,
    GetTransactionRequestAttributeDefinition200ResponseAttributesInnerToJSON,
} from '../models/index';

export interface CreateOrUpdateTransactionAttributeDefinitionRequest {
    bankid: string;
    createOrUpdateTransactionRequestAttributeDefinitionRequest: CreateOrUpdateTransactionRequestAttributeDefinitionRequest;
}

export interface CreateTransactionAttributeRequest {
    bankid: string;
    accountid: string;
    transactionid: string;
    createPersonalDataFieldRequest: CreatePersonalDataFieldRequest;
}

export interface DeleteTransactionAttributeDefinitionRequest {
    bankid: string;
    attributedefinitionid: string;
}

export interface GetTransactionAttributeByIdRequest {
    bankid: string;
    accountid: string;
    transactionid: string;
    attributeid: string;
}

export interface GetTransactionAttributeDefinitionRequest {
    bankid: string;
}

export interface GetTransactionAttributesRequest {
    bankid: string;
    accountid: string;
    transactionid: string;
}

export interface UpdateTransactionAttributeRequest {
    bankid: string;
    accountid: string;
    transactionid: string;
    accountattributeid: string;
    createPersonalDataFieldRequest: CreatePersonalDataFieldRequest;
}

/**
 * 
 */
export class TransactionAttributeApi extends runtime.BaseAPI {

    /**
     * Creates request options for createOrUpdateTransactionAttributeDefinition without sending the request
     */
    async createOrUpdateTransactionAttributeDefinitionRequestOpts(requestParameters: CreateOrUpdateTransactionAttributeDefinitionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bankid'] == null) {
            throw new runtime.RequiredError(
                'bankid',
                'Required parameter "bankid" was null or undefined when calling createOrUpdateTransactionAttributeDefinition().'
            );
        }

        if (requestParameters['createOrUpdateTransactionRequestAttributeDefinitionRequest'] == null) {
            throw new runtime.RequiredError(
                'createOrUpdateTransactionRequestAttributeDefinitionRequest',
                'Required parameter "createOrUpdateTransactionRequestAttributeDefinitionRequest" was null or undefined when calling createOrUpdateTransactionAttributeDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // GatewayLogin authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["DirectLogin"] = await this.configuration.apiKey("DirectLogin"); // DirectLogin authentication
        }


        let urlPath = `/obp/v4.0.0/banks/{bankid}/attribute-definitions/transaction`;
        urlPath = urlPath.replace(`{${"bankid"}}`, encodeURIComponent(String(requestParameters['bankid'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrUpdateTransactionRequestAttributeDefinitionRequestToJSON(requestParameters['createOrUpdateTransactionRequestAttributeDefinitionRequest']),
        };
    }

    /**
     * <p>Create or Update Transaction Attribute Definition</p> <p>The category field must be Transaction</p> <p>The type field must be one of; DOUBLE, STRING, INTEGER and DATE_WITH_DAY</p> <p>User Authentication is Required. The User must be logged in. The Application must also be authenticated.</p> <p><strong>URL Parameters:</strong></p> <p><a href=\"/glossary#Bank.bank_id\">BANK_ID</a>: gh.29.uk</p> <p><strong>JSON response body fields:</strong></p> <p><a href=\"/glossary#alias\"><strong>alias</strong></a>:</p> <p><a href=\"/glossary#attribute_definition_id\"><strong>attribute_definition_id</strong></a>:</p> <p><a href=\"/glossary#\"><strong>bank_id</strong></a>: gh.29.uk</p> <p><a href=\"/glossary#can_be_seen_on_views\"><strong>can_be_seen_on_views</strong></a>: false</p> <p><a href=\"/glossary#category\"><strong>category</strong></a>:</p> <p><a href=\"/glossary#description\"><strong>description</strong></a>: Description of the object. Maximum length is 2000. It can be any characters here.</p> <p><a href=\"/glossary#is_active\"><strong>is_active</strong></a>: false</p> <p><a href=\"/glossary#name\"><strong>name</strong></a>: ACCOUNT_MANAGEMENT_FEE</p> <p><a href=\"/glossary#type\"><strong>type</strong></a>:</p> 
     * Create or Update Transaction Attribute Definition
     */
    async createOrUpdateTransactionAttributeDefinitionRaw(requestParameters: CreateOrUpdateTransactionAttributeDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTransactionRequestAttributeDefinition200ResponseAttributesInner>> {
        const requestOptions = await this.createOrUpdateTransactionAttributeDefinitionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTransactionRequestAttributeDefinition200ResponseAttributesInnerFromJSON(jsonValue));
    }

    /**
     * <p>Create or Update Transaction Attribute Definition</p> <p>The category field must be Transaction</p> <p>The type field must be one of; DOUBLE, STRING, INTEGER and DATE_WITH_DAY</p> <p>User Authentication is Required. The User must be logged in. The Application must also be authenticated.</p> <p><strong>URL Parameters:</strong></p> <p><a href=\"/glossary#Bank.bank_id\">BANK_ID</a>: gh.29.uk</p> <p><strong>JSON response body fields:</strong></p> <p><a href=\"/glossary#alias\"><strong>alias</strong></a>:</p> <p><a href=\"/glossary#attribute_definition_id\"><strong>attribute_definition_id</strong></a>:</p> <p><a href=\"/glossary#\"><strong>bank_id</strong></a>: gh.29.uk</p> <p><a href=\"/glossary#can_be_seen_on_views\"><strong>can_be_seen_on_views</strong></a>: false</p> <p><a href=\"/glossary#category\"><strong>category</strong></a>:</p> <p><a href=\"/glossary#description\"><strong>description</strong></a>: Description of the object. Maximum length is 2000. It can be any characters here.</p> <p><a href=\"/glossary#is_active\"><strong>is_active</strong></a>: false</p> <p><a href=\"/glossary#name\"><strong>name</strong></a>: ACCOUNT_MANAGEMENT_FEE</p> <p><a href=\"/glossary#type\"><strong>type</strong></a>:</p> 
     * Create or Update Transaction Attribute Definition
     */
    async createOrUpdateTransactionAttributeDefinition(requestParameters: CreateOrUpdateTransactionAttributeDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTransactionRequestAttributeDefinition200ResponseAttributesInner> {
        const response = await this.createOrUpdateTransactionAttributeDefinitionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTransactionAttribute without sending the request
     */
    async createTransactionAttributeRequestOpts(requestParameters: CreateTransactionAttributeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bankid'] == null) {
            throw new runtime.RequiredError(
                'bankid',
                'Required parameter "bankid" was null or undefined when calling createTransactionAttribute().'
            );
        }

        if (requestParameters['accountid'] == null) {
            throw new runtime.RequiredError(
                'accountid',
                'Required parameter "accountid" was null or undefined when calling createTransactionAttribute().'
            );
        }

        if (requestParameters['transactionid'] == null) {
            throw new runtime.RequiredError(
                'transactionid',
                'Required parameter "transactionid" was null or undefined when calling createTransactionAttribute().'
            );
        }

        if (requestParameters['createPersonalDataFieldRequest'] == null) {
            throw new runtime.RequiredError(
                'createPersonalDataFieldRequest',
                'Required parameter "createPersonalDataFieldRequest" was null or undefined when calling createTransactionAttribute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // GatewayLogin authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["DirectLogin"] = await this.configuration.apiKey("DirectLogin"); // DirectLogin authentication
        }


        let urlPath = `/obp/v4.0.0/banks/{bankid}/accounts/{accountid}/transactions/{transactionid}/attribute`;
        urlPath = urlPath.replace(`{${"bankid"}}`, encodeURIComponent(String(requestParameters['bankid'])));
        urlPath = urlPath.replace(`{${"accountid"}}`, encodeURIComponent(String(requestParameters['accountid'])));
        urlPath = urlPath.replace(`{${"transactionid"}}`, encodeURIComponent(String(requestParameters['transactionid'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePersonalDataFieldRequestToJSON(requestParameters['createPersonalDataFieldRequest']),
        };
    }

    /**
     * <p>Create Transaction Attribute</p> <p>The type field must be one of &quot;STRING&quot;, &quot;INTEGER&quot;, &quot;DOUBLE&quot; or DATE_WITH_DAY&quot;</p> <p>User Authentication is Required. The User must be logged in. The Application must also be authenticated.</p> <p><strong>URL Parameters:</strong></p> <p><a href=\"/glossary#Account.account_id\">ACCOUNT_ID</a>: 8ca8a7e4-6d02-40e3-a129-0b2bf89de9f0</p> <p><a href=\"/glossary#Bank.bank_id\">BANK_ID</a>: gh.29.uk</p> <p><a href=\"/glossary#transaction_ids\">TRANSACTION_ID</a>: 2fg8a7e4-6d02-40e3-a129-0b2bf89de8ub</p> <p><strong>JSON request body fields:</strong></p> <p><a href=\"/glossary#name\"><strong>name</strong></a>: ACCOUNT_MANAGEMENT_FEE</p> <p><a href=\"/glossary#type\"><strong>type</strong></a>:</p> <p><a href=\"/glossary#\"><strong>value</strong></a>: 5987953</p> <p><strong>JSON response body fields:</strong></p> <p><a href=\"/glossary#name\"><strong>name</strong></a>: ACCOUNT_MANAGEMENT_FEE</p> <p><a href=\"/glossary#\"><strong>transaction_attribute_id</strong></a>: 7uy8a7e4-6d02-40e3-a129-0b2bf89de8uh</p> <p><a href=\"/glossary#type\"><strong>type</strong></a>:</p> <p><a href=\"/glossary#\"><strong>value</strong></a>: 5987953</p> 
     * Create Transaction Attribute
     */
    async createTransactionAttributeRaw(requestParameters: CreateTransactionAttributeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCoreTransactionsForBankAccount200ResponseTransactionsInnerTransactionAttributesInner>> {
        const requestOptions = await this.createTransactionAttributeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCoreTransactionsForBankAccount200ResponseTransactionsInnerTransactionAttributesInnerFromJSON(jsonValue));
    }

    /**
     * <p>Create Transaction Attribute</p> <p>The type field must be one of &quot;STRING&quot;, &quot;INTEGER&quot;, &quot;DOUBLE&quot; or DATE_WITH_DAY&quot;</p> <p>User Authentication is Required. The User must be logged in. The Application must also be authenticated.</p> <p><strong>URL Parameters:</strong></p> <p><a href=\"/glossary#Account.account_id\">ACCOUNT_ID</a>: 8ca8a7e4-6d02-40e3-a129-0b2bf89de9f0</p> <p><a href=\"/glossary#Bank.bank_id\">BANK_ID</a>: gh.29.uk</p> <p><a href=\"/glossary#transaction_ids\">TRANSACTION_ID</a>: 2fg8a7e4-6d02-40e3-a129-0b2bf89de8ub</p> <p><strong>JSON request body fields:</strong></p> <p><a href=\"/glossary#name\"><strong>name</strong></a>: ACCOUNT_MANAGEMENT_FEE</p> <p><a href=\"/glossary#type\"><strong>type</strong></a>:</p> <p><a href=\"/glossary#\"><strong>value</strong></a>: 5987953</p> <p><strong>JSON response body fields:</strong></p> <p><a href=\"/glossary#name\"><strong>name</strong></a>: ACCOUNT_MANAGEMENT_FEE</p> <p><a href=\"/glossary#\"><strong>transaction_attribute_id</strong></a>: 7uy8a7e4-6d02-40e3-a129-0b2bf89de8uh</p> <p><a href=\"/glossary#type\"><strong>type</strong></a>:</p> <p><a href=\"/glossary#\"><strong>value</strong></a>: 5987953</p> 
     * Create Transaction Attribute
     */
    async createTransactionAttribute(requestParameters: CreateTransactionAttributeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCoreTransactionsForBankAccount200ResponseTransactionsInnerTransactionAttributesInner> {
        const response = await this.createTransactionAttributeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTransactionAttributeDefinition without sending the request
     */
    async deleteTransactionAttributeDefinitionRequestOpts(requestParameters: DeleteTransactionAttributeDefinitionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bankid'] == null) {
            throw new runtime.RequiredError(
                'bankid',
                'Required parameter "bankid" was null or undefined when calling deleteTransactionAttributeDefinition().'
            );
        }

        if (requestParameters['attributedefinitionid'] == null) {
            throw new runtime.RequiredError(
                'attributedefinitionid',
                'Required parameter "attributedefinitionid" was null or undefined when calling deleteTransactionAttributeDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // GatewayLogin authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["DirectLogin"] = await this.configuration.apiKey("DirectLogin"); // DirectLogin authentication
        }


        let urlPath = `/obp/v4.0.0/banks/{bankid}/attribute-definitions/{attributedefinitionid}/transaction`;
        urlPath = urlPath.replace(`{${"bankid"}}`, encodeURIComponent(String(requestParameters['bankid'])));
        urlPath = urlPath.replace(`{${"attributedefinitionid"}}`, encodeURIComponent(String(requestParameters['attributedefinitionid'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * <p>Delete Transaction Attribute Definition by ATTRIBUTE_DEFINITION_ID</p> <p>User Authentication is Required. The User must be logged in. The Application must also be authenticated.</p> <p><strong>URL Parameters:</strong></p> <p><a href=\"/glossary#attribute_definition_id\">ATTRIBUTE_DEFINITION_ID</a>:</p> <p><a href=\"/glossary#Bank.bank_id\">BANK_ID</a>: gh.29.uk</p> <p><strong>JSON response body fields:</strong></p> 
     * Delete Transaction Attribute Definition
     */
    async deleteTransactionAttributeDefinitionRaw(requestParameters: DeleteTransactionAttributeDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTransactionAttributeDefinitionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * <p>Delete Transaction Attribute Definition by ATTRIBUTE_DEFINITION_ID</p> <p>User Authentication is Required. The User must be logged in. The Application must also be authenticated.</p> <p><strong>URL Parameters:</strong></p> <p><a href=\"/glossary#attribute_definition_id\">ATTRIBUTE_DEFINITION_ID</a>:</p> <p><a href=\"/glossary#Bank.bank_id\">BANK_ID</a>: gh.29.uk</p> <p><strong>JSON response body fields:</strong></p> 
     * Delete Transaction Attribute Definition
     */
    async deleteTransactionAttributeDefinition(requestParameters: DeleteTransactionAttributeDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTransactionAttributeDefinitionRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getTransactionAttributeById without sending the request
     */
    async getTransactionAttributeByIdRequestOpts(requestParameters: GetTransactionAttributeByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bankid'] == null) {
            throw new runtime.RequiredError(
                'bankid',
                'Required parameter "bankid" was null or undefined when calling getTransactionAttributeById().'
            );
        }

        if (requestParameters['accountid'] == null) {
            throw new runtime.RequiredError(
                'accountid',
                'Required parameter "accountid" was null or undefined when calling getTransactionAttributeById().'
            );
        }

        if (requestParameters['transactionid'] == null) {
            throw new runtime.RequiredError(
                'transactionid',
                'Required parameter "transactionid" was null or undefined when calling getTransactionAttributeById().'
            );
        }

        if (requestParameters['attributeid'] == null) {
            throw new runtime.RequiredError(
                'attributeid',
                'Required parameter "attributeid" was null or undefined when calling getTransactionAttributeById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // GatewayLogin authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["DirectLogin"] = await this.configuration.apiKey("DirectLogin"); // DirectLogin authentication
        }


        let urlPath = `/obp/v4.0.0/banks/{bankid}/accounts/{accountid}/transactions/{transactionid}/attributes/{attributeid}`;
        urlPath = urlPath.replace(`{${"bankid"}}`, encodeURIComponent(String(requestParameters['bankid'])));
        urlPath = urlPath.replace(`{${"accountid"}}`, encodeURIComponent(String(requestParameters['accountid'])));
        urlPath = urlPath.replace(`{${"transactionid"}}`, encodeURIComponent(String(requestParameters['transactionid'])));
        urlPath = urlPath.replace(`{${"attributeid"}}`, encodeURIComponent(String(requestParameters['attributeid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * <p>Get Transaction Attribute By Id</p> <p>User Authentication is Required. The User must be logged in. The Application must also be authenticated.</p> <p><strong>URL Parameters:</strong></p> <p><a href=\"/glossary#Account.account_id\">ACCOUNT_ID</a>: 8ca8a7e4-6d02-40e3-a129-0b2bf89de9f0</p> <p><a href=\"/glossary#Adapter.card_attribute_id\">ATTRIBUTE_ID</a>:</p> <p><a href=\"/glossary#Bank.bank_id\">BANK_ID</a>: gh.29.uk</p> <p><a href=\"/glossary#transaction_ids\">TRANSACTION_ID</a>: 2fg8a7e4-6d02-40e3-a129-0b2bf89de8ub</p> <p><strong>JSON response body fields:</strong></p> <p><a href=\"/glossary#name\"><strong>name</strong></a>: ACCOUNT_MANAGEMENT_FEE</p> <p><a href=\"/glossary#\"><strong>transaction_attribute_id</strong></a>: 7uy8a7e4-6d02-40e3-a129-0b2bf89de8uh</p> <p><a href=\"/glossary#type\"><strong>type</strong></a>:</p> <p><a href=\"/glossary#\"><strong>value</strong></a>: 5987953</p> 
     * Get Transaction Attribute By Id
     */
    async getTransactionAttributeByIdRaw(requestParameters: GetTransactionAttributeByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCoreTransactionsForBankAccount200ResponseTransactionsInnerTransactionAttributesInner>> {
        const requestOptions = await this.getTransactionAttributeByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCoreTransactionsForBankAccount200ResponseTransactionsInnerTransactionAttributesInnerFromJSON(jsonValue));
    }

    /**
     * <p>Get Transaction Attribute By Id</p> <p>User Authentication is Required. The User must be logged in. The Application must also be authenticated.</p> <p><strong>URL Parameters:</strong></p> <p><a href=\"/glossary#Account.account_id\">ACCOUNT_ID</a>: 8ca8a7e4-6d02-40e3-a129-0b2bf89de9f0</p> <p><a href=\"/glossary#Adapter.card_attribute_id\">ATTRIBUTE_ID</a>:</p> <p><a href=\"/glossary#Bank.bank_id\">BANK_ID</a>: gh.29.uk</p> <p><a href=\"/glossary#transaction_ids\">TRANSACTION_ID</a>: 2fg8a7e4-6d02-40e3-a129-0b2bf89de8ub</p> <p><strong>JSON response body fields:</strong></p> <p><a href=\"/glossary#name\"><strong>name</strong></a>: ACCOUNT_MANAGEMENT_FEE</p> <p><a href=\"/glossary#\"><strong>transaction_attribute_id</strong></a>: 7uy8a7e4-6d02-40e3-a129-0b2bf89de8uh</p> <p><a href=\"/glossary#type\"><strong>type</strong></a>:</p> <p><a href=\"/glossary#\"><strong>value</strong></a>: 5987953</p> 
     * Get Transaction Attribute By Id
     */
    async getTransactionAttributeById(requestParameters: GetTransactionAttributeByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCoreTransactionsForBankAccount200ResponseTransactionsInnerTransactionAttributesInner> {
        const response = await this.getTransactionAttributeByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTransactionAttributeDefinition without sending the request
     */
    async getTransactionAttributeDefinitionRequestOpts(requestParameters: GetTransactionAttributeDefinitionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bankid'] == null) {
            throw new runtime.RequiredError(
                'bankid',
                'Required parameter "bankid" was null or undefined when calling getTransactionAttributeDefinition().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // GatewayLogin authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["DirectLogin"] = await this.configuration.apiKey("DirectLogin"); // DirectLogin authentication
        }


        let urlPath = `/obp/v4.0.0/banks/{bankid}/attribute-definitions/transaction`;
        urlPath = urlPath.replace(`{${"bankid"}}`, encodeURIComponent(String(requestParameters['bankid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * <p>Get Transaction Attribute Definition</p> <p>User Authentication is Required. The User must be logged in. The Application must also be authenticated.</p> <p><strong>URL Parameters:</strong></p> <p><a href=\"/glossary#Bank.bank_id\">BANK_ID</a>: gh.29.uk</p> <p><strong>JSON response body fields:</strong></p> <p><a href=\"/glossary#alias\"><strong>alias</strong></a>:</p> <p><a href=\"/glossary#attribute_definition_id\"><strong>attribute_definition_id</strong></a>:</p> <p><a href=\"/glossary#attributes\"><strong>attributes</strong></a>: attribute value in form of (name, value)</p> <p><a href=\"/glossary#\"><strong>bank_id</strong></a>: gh.29.uk</p> <p><a href=\"/glossary#can_be_seen_on_views\"><strong>can_be_seen_on_views</strong></a>: false</p> <p><a href=\"/glossary#category\"><strong>category</strong></a>:</p> <p><a href=\"/glossary#description\"><strong>description</strong></a>: Description of the object. Maximum length is 2000. It can be any characters here.</p> <p><a href=\"/glossary#is_active\"><strong>is_active</strong></a>: false</p> <p><a href=\"/glossary#name\"><strong>name</strong></a>: ACCOUNT_MANAGEMENT_FEE</p> <p><a href=\"/glossary#type\"><strong>type</strong></a>:</p> 
     * Get Transaction Attribute Definition
     */
    async getTransactionAttributeDefinitionRaw(requestParameters: GetTransactionAttributeDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTransactionRequestAttributeDefinition200Response>> {
        const requestOptions = await this.getTransactionAttributeDefinitionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTransactionRequestAttributeDefinition200ResponseFromJSON(jsonValue));
    }

    /**
     * <p>Get Transaction Attribute Definition</p> <p>User Authentication is Required. The User must be logged in. The Application must also be authenticated.</p> <p><strong>URL Parameters:</strong></p> <p><a href=\"/glossary#Bank.bank_id\">BANK_ID</a>: gh.29.uk</p> <p><strong>JSON response body fields:</strong></p> <p><a href=\"/glossary#alias\"><strong>alias</strong></a>:</p> <p><a href=\"/glossary#attribute_definition_id\"><strong>attribute_definition_id</strong></a>:</p> <p><a href=\"/glossary#attributes\"><strong>attributes</strong></a>: attribute value in form of (name, value)</p> <p><a href=\"/glossary#\"><strong>bank_id</strong></a>: gh.29.uk</p> <p><a href=\"/glossary#can_be_seen_on_views\"><strong>can_be_seen_on_views</strong></a>: false</p> <p><a href=\"/glossary#category\"><strong>category</strong></a>:</p> <p><a href=\"/glossary#description\"><strong>description</strong></a>: Description of the object. Maximum length is 2000. It can be any characters here.</p> <p><a href=\"/glossary#is_active\"><strong>is_active</strong></a>: false</p> <p><a href=\"/glossary#name\"><strong>name</strong></a>: ACCOUNT_MANAGEMENT_FEE</p> <p><a href=\"/glossary#type\"><strong>type</strong></a>:</p> 
     * Get Transaction Attribute Definition
     */
    async getTransactionAttributeDefinition(requestParameters: GetTransactionAttributeDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTransactionRequestAttributeDefinition200Response> {
        const response = await this.getTransactionAttributeDefinitionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTransactionAttributes without sending the request
     */
    async getTransactionAttributesRequestOpts(requestParameters: GetTransactionAttributesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bankid'] == null) {
            throw new runtime.RequiredError(
                'bankid',
                'Required parameter "bankid" was null or undefined when calling getTransactionAttributes().'
            );
        }

        if (requestParameters['accountid'] == null) {
            throw new runtime.RequiredError(
                'accountid',
                'Required parameter "accountid" was null or undefined when calling getTransactionAttributes().'
            );
        }

        if (requestParameters['transactionid'] == null) {
            throw new runtime.RequiredError(
                'transactionid',
                'Required parameter "transactionid" was null or undefined when calling getTransactionAttributes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // GatewayLogin authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["DirectLogin"] = await this.configuration.apiKey("DirectLogin"); // DirectLogin authentication
        }


        let urlPath = `/obp/v4.0.0/banks/{bankid}/accounts/{accountid}/transactions/{transactionid}/attributes`;
        urlPath = urlPath.replace(`{${"bankid"}}`, encodeURIComponent(String(requestParameters['bankid'])));
        urlPath = urlPath.replace(`{${"accountid"}}`, encodeURIComponent(String(requestParameters['accountid'])));
        urlPath = urlPath.replace(`{${"transactionid"}}`, encodeURIComponent(String(requestParameters['transactionid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * <p>Get Transaction Attributes</p> <p>User Authentication is Required. The User must be logged in. The Application must also be authenticated.</p> <p><strong>URL Parameters:</strong></p> <p><a href=\"/glossary#Account.account_id\">ACCOUNT_ID</a>: 8ca8a7e4-6d02-40e3-a129-0b2bf89de9f0</p> <p><a href=\"/glossary#Bank.bank_id\">BANK_ID</a>: gh.29.uk</p> <p><a href=\"/glossary#transaction_ids\">TRANSACTION_ID</a>: 2fg8a7e4-6d02-40e3-a129-0b2bf89de8ub</p> <p><strong>JSON response body fields:</strong></p> <p><a href=\"/glossary#name\"><strong>name</strong></a>: ACCOUNT_MANAGEMENT_FEE</p> <p><a href=\"/glossary#\"><strong>transaction_attribute_id</strong></a>: 7uy8a7e4-6d02-40e3-a129-0b2bf89de8uh</p> <p><a href=\"/glossary#transaction_attributes\"><strong>transaction_attributes</strong></a>:</p> <p><a href=\"/glossary#type\"><strong>type</strong></a>:</p> <p><a href=\"/glossary#\"><strong>value</strong></a>: 5987953</p> 
     * Get Transaction Attributes
     */
    async getTransactionAttributesRaw(requestParameters: GetTransactionAttributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTransactionAttributes200Response>> {
        const requestOptions = await this.getTransactionAttributesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTransactionAttributes200ResponseFromJSON(jsonValue));
    }

    /**
     * <p>Get Transaction Attributes</p> <p>User Authentication is Required. The User must be logged in. The Application must also be authenticated.</p> <p><strong>URL Parameters:</strong></p> <p><a href=\"/glossary#Account.account_id\">ACCOUNT_ID</a>: 8ca8a7e4-6d02-40e3-a129-0b2bf89de9f0</p> <p><a href=\"/glossary#Bank.bank_id\">BANK_ID</a>: gh.29.uk</p> <p><a href=\"/glossary#transaction_ids\">TRANSACTION_ID</a>: 2fg8a7e4-6d02-40e3-a129-0b2bf89de8ub</p> <p><strong>JSON response body fields:</strong></p> <p><a href=\"/glossary#name\"><strong>name</strong></a>: ACCOUNT_MANAGEMENT_FEE</p> <p><a href=\"/glossary#\"><strong>transaction_attribute_id</strong></a>: 7uy8a7e4-6d02-40e3-a129-0b2bf89de8uh</p> <p><a href=\"/glossary#transaction_attributes\"><strong>transaction_attributes</strong></a>:</p> <p><a href=\"/glossary#type\"><strong>type</strong></a>:</p> <p><a href=\"/glossary#\"><strong>value</strong></a>: 5987953</p> 
     * Get Transaction Attributes
     */
    async getTransactionAttributes(requestParameters: GetTransactionAttributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTransactionAttributes200Response> {
        const response = await this.getTransactionAttributesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTransactionAttribute without sending the request
     */
    async updateTransactionAttributeRequestOpts(requestParameters: UpdateTransactionAttributeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bankid'] == null) {
            throw new runtime.RequiredError(
                'bankid',
                'Required parameter "bankid" was null or undefined when calling updateTransactionAttribute().'
            );
        }

        if (requestParameters['accountid'] == null) {
            throw new runtime.RequiredError(
                'accountid',
                'Required parameter "accountid" was null or undefined when calling updateTransactionAttribute().'
            );
        }

        if (requestParameters['transactionid'] == null) {
            throw new runtime.RequiredError(
                'transactionid',
                'Required parameter "transactionid" was null or undefined when calling updateTransactionAttribute().'
            );
        }

        if (requestParameters['accountattributeid'] == null) {
            throw new runtime.RequiredError(
                'accountattributeid',
                'Required parameter "accountattributeid" was null or undefined when calling updateTransactionAttribute().'
            );
        }

        if (requestParameters['createPersonalDataFieldRequest'] == null) {
            throw new runtime.RequiredError(
                'createPersonalDataFieldRequest',
                'Required parameter "createPersonalDataFieldRequest" was null or undefined when calling updateTransactionAttribute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // GatewayLogin authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["DirectLogin"] = await this.configuration.apiKey("DirectLogin"); // DirectLogin authentication
        }


        let urlPath = `/obp/v4.0.0/banks/{bankid}/accounts/{accountid}/transactions/{transactionid}/attributes/{accountattributeid}`;
        urlPath = urlPath.replace(`{${"bankid"}}`, encodeURIComponent(String(requestParameters['bankid'])));
        urlPath = urlPath.replace(`{${"accountid"}}`, encodeURIComponent(String(requestParameters['accountid'])));
        urlPath = urlPath.replace(`{${"transactionid"}}`, encodeURIComponent(String(requestParameters['transactionid'])));
        urlPath = urlPath.replace(`{${"accountattributeid"}}`, encodeURIComponent(String(requestParameters['accountattributeid'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePersonalDataFieldRequestToJSON(requestParameters['createPersonalDataFieldRequest']),
        };
    }

    /**
     * <p>Update Transaction Attribute</p> <p>User Authentication is Required. The User must be logged in. The Application must also be authenticated.</p> <p><strong>URL Parameters:</strong></p> <p><a href=\"/glossary#account_attribute_id\">ACCOUNT_ATTRIBUTE_ID</a>:</p> <p><a href=\"/glossary#Account.account_id\">ACCOUNT_ID</a>: 8ca8a7e4-6d02-40e3-a129-0b2bf89de9f0</p> <p><a href=\"/glossary#Bank.bank_id\">BANK_ID</a>: gh.29.uk</p> <p><a href=\"/glossary#transaction_ids\">TRANSACTION_ID</a>: 2fg8a7e4-6d02-40e3-a129-0b2bf89de8ub</p> <p><strong>JSON response body fields:</strong></p> <p><a href=\"/glossary#name\"><strong>name</strong></a>: ACCOUNT_MANAGEMENT_FEE</p> <p><a href=\"/glossary#\"><strong>transaction_attribute_id</strong></a>: 7uy8a7e4-6d02-40e3-a129-0b2bf89de8uh</p> <p><a href=\"/glossary#type\"><strong>type</strong></a>:</p> <p><a href=\"/glossary#\"><strong>value</strong></a>: 5987953</p> 
     * Update Transaction Attribute
     */
    async updateTransactionAttributeRaw(requestParameters: UpdateTransactionAttributeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCoreTransactionsForBankAccount200ResponseTransactionsInnerTransactionAttributesInner>> {
        const requestOptions = await this.updateTransactionAttributeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCoreTransactionsForBankAccount200ResponseTransactionsInnerTransactionAttributesInnerFromJSON(jsonValue));
    }

    /**
     * <p>Update Transaction Attribute</p> <p>User Authentication is Required. The User must be logged in. The Application must also be authenticated.</p> <p><strong>URL Parameters:</strong></p> <p><a href=\"/glossary#account_attribute_id\">ACCOUNT_ATTRIBUTE_ID</a>:</p> <p><a href=\"/glossary#Account.account_id\">ACCOUNT_ID</a>: 8ca8a7e4-6d02-40e3-a129-0b2bf89de9f0</p> <p><a href=\"/glossary#Bank.bank_id\">BANK_ID</a>: gh.29.uk</p> <p><a href=\"/glossary#transaction_ids\">TRANSACTION_ID</a>: 2fg8a7e4-6d02-40e3-a129-0b2bf89de8ub</p> <p><strong>JSON response body fields:</strong></p> <p><a href=\"/glossary#name\"><strong>name</strong></a>: ACCOUNT_MANAGEMENT_FEE</p> <p><a href=\"/glossary#\"><strong>transaction_attribute_id</strong></a>: 7uy8a7e4-6d02-40e3-a129-0b2bf89de8uh</p> <p><a href=\"/glossary#type\"><strong>type</strong></a>:</p> <p><a href=\"/glossary#\"><strong>value</strong></a>: 5987953</p> 
     * Update Transaction Attribute
     */
    async updateTransactionAttribute(requestParameters: UpdateTransactionAttributeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCoreTransactionsForBankAccount200ResponseTransactionsInnerTransactionAttributesInner> {
        const response = await this.updateTransactionAttributeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
