/*
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openbankproject.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openbankproject.model.GetAdapterInfo200ResponseBackendMessagesInner;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetAdapterInfo200Response
 */
class GetAdapterInfo200ResponseTest {
    private final GetAdapterInfo200Response model = new GetAdapterInfo200Response();

    /**
     * Model tests for GetAdapterInfo200Response
     */
    @Test
    void testGetAdapterInfo200Response() {
        // TODO: test GetAdapterInfo200Response
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'backendMessages'
     */
    @Test
    void backendMessagesTest() {
        // TODO: test backendMessages
    }

    /**
     * Test the property 'totalDuration'
     */
    @Test
    void totalDurationTest() {
        // TODO: test totalDuration
    }

    /**
     * Test the property 'version'
     */
    @Test
    void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'date'
     */
    @Test
    void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'gitCommit'
     */
    @Test
    void gitCommitTest() {
        // TODO: test gitCommit
    }

}
