/*
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openbankproject.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetAtmAttribute200Response
 */
class GetAtmAttribute200ResponseTest {
    private final GetAtmAttribute200Response model = new GetAtmAttribute200Response();

    /**
     * Model tests for GetAtmAttribute200Response
     */
    @Test
    void testGetAtmAttribute200Response() {
        // TODO: test GetAtmAttribute200Response
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'atmId'
     */
    @Test
    void atmIdTest() {
        // TODO: test atmId
    }

    /**
     * Test the property 'bankId'
     */
    @Test
    void bankIdTest() {
        // TODO: test bankId
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'atmAttributeId'
     */
    @Test
    void atmAttributeIdTest() {
        // TODO: test atmAttributeId
    }

    /**
     * Test the property 'value'
     */
    @Test
    void valueTest() {
        // TODO: test value
    }

}
