/*
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openbankproject.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openbankproject.model.CreateTransactionRequestCounterparty200ResponseFrom;
import com.openbankproject.model.GetFastFirehoseAccountsAtOneBank200ResponseAccountsInnerAccountAttributesInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetAccountDirectory200ResponseAccountsInner
 */
class GetAccountDirectory200ResponseAccountsInnerTest {
    private final GetAccountDirectory200ResponseAccountsInner model = new GetAccountDirectory200ResponseAccountsInner();

    /**
     * Model tests for GetAccountDirectory200ResponseAccountsInner
     */
    @Test
    void testGetAccountDirectory200ResponseAccountsInner() {
        // TODO: test GetAccountDirectory200ResponseAccountsInner
    }

    /**
     * Test the property 'accountAttributes'
     */
    @Test
    void accountAttributesTest() {
        // TODO: test accountAttributes
    }

    /**
     * Test the property 'branchId'
     */
    @Test
    void branchIdTest() {
        // TODO: test branchId
    }

    /**
     * Test the property 'accountRoutings'
     */
    @Test
    void accountRoutingsTest() {
        // TODO: test accountRoutings
    }

    /**
     * Test the property 'label'
     */
    @Test
    void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'bankId'
     */
    @Test
    void bankIdTest() {
        // TODO: test bankId
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'viewIds'
     */
    @Test
    void viewIdsTest() {
        // TODO: test viewIds
    }

}
