/*
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openbankproject.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetMigrations200ResponseMigrationScriptLogsInner
 */
class GetMigrations200ResponseMigrationScriptLogsInnerTest {
    private final GetMigrations200ResponseMigrationScriptLogsInner model = new GetMigrations200ResponseMigrationScriptLogsInner();

    /**
     * Model tests for GetMigrations200ResponseMigrationScriptLogsInner
     */
    @Test
    void testGetMigrations200ResponseMigrationScriptLogsInner() {
        // TODO: test GetMigrations200ResponseMigrationScriptLogsInner
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'commitId'
     */
    @Test
    void commitIdTest() {
        // TODO: test commitId
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'migrationScriptLogId'
     */
    @Test
    void migrationScriptLogIdTest() {
        // TODO: test migrationScriptLogId
    }

    /**
     * Test the property 'durationInMs'
     */
    @Test
    void durationInMsTest() {
        // TODO: test durationInMs
    }

    /**
     * Test the property 'remark'
     */
    @Test
    void remarkTest() {
        // TODO: test remark
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'isSuccessful'
     */
    @Test
    void isSuccessfulTest() {
        // TODO: test isSuccessful
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    void updatedAtTest() {
        // TODO: test updatedAt
    }

}
