/*
 * Open Bank Project API v6.0.0
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openbankproject.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetStatusOfCreditCardOrder200ResponseCardsInner
 */
class GetStatusOfCreditCardOrder200ResponseCardsInnerTest {
    private final GetStatusOfCreditCardOrder200ResponseCardsInner model = new GetStatusOfCreditCardOrder200ResponseCardsInner();

    /**
     * Model tests for GetStatusOfCreditCardOrder200ResponseCardsInner
     */
    @Test
    void testGetStatusOfCreditCardOrder200ResponseCardsInner() {
        // TODO: test GetStatusOfCreditCardOrder200ResponseCardsInner
    }

    /**
     * Test the property 'useType'
     */
    @Test
    void useTypeTest() {
        // TODO: test useType
    }

    /**
     * Test the property 'cardDescription'
     */
    @Test
    void cardDescriptionTest() {
        // TODO: test cardDescription
    }

    /**
     * Test the property 'cardType'
     */
    @Test
    void cardTypeTest() {
        // TODO: test cardType
    }

}
