/*
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenBankProject.Model;
using OpenBankProject.Client;
using System.Reflection;

namespace OpenBankProject.Test.Model
{
    /// <summary>
    ///  Class for testing GetBankAccountsBalances200ResponseAccountsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetBankAccountsBalances200ResponseAccountsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetBankAccountsBalances200ResponseAccountsInner
        //private GetBankAccountsBalances200ResponseAccountsInner instance;

        public GetBankAccountsBalances200ResponseAccountsInnerTests()
        {
            // TODO uncomment below to create an instance of GetBankAccountsBalances200ResponseAccountsInner
            //instance = new GetBankAccountsBalances200ResponseAccountsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetBankAccountsBalances200ResponseAccountsInner
        /// </summary>
        [Fact]
        public void GetBankAccountsBalances200ResponseAccountsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetBankAccountsBalances200ResponseAccountsInner
            //Assert.IsType<GetBankAccountsBalances200ResponseAccountsInner>(instance);
        }

        /// <summary>
        /// Test the property 'AccountRoutings'
        /// </summary>
        [Fact]
        public void AccountRoutingsTest()
        {
            // TODO unit test for the property 'AccountRoutings'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'BankId'
        /// </summary>
        [Fact]
        public void BankIdTest()
        {
            // TODO unit test for the property 'BankId'
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }

        /// <summary>
        /// Test the property 'Balances'
        /// </summary>
        [Fact]
        public void BalancesTest()
        {
            // TODO unit test for the property 'Balances'
        }
    }
}
