/*
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenBankProject.Model;
using OpenBankProject.Client;
using System.Reflection;

namespace OpenBankProject.Test.Model
{
    /// <summary>
    ///  Class for testing GetMyCorrelatedEntities200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetMyCorrelatedEntities200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetMyCorrelatedEntities200Response
        //private GetMyCorrelatedEntities200Response instance;

        public GetMyCorrelatedEntities200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetMyCorrelatedEntities200Response
            //instance = new GetMyCorrelatedEntities200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetMyCorrelatedEntities200Response
        /// </summary>
        [Fact]
        public void GetMyCorrelatedEntities200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetMyCorrelatedEntities200Response
            //Assert.IsType<GetMyCorrelatedEntities200Response>(instance);
        }

        /// <summary>
        /// Test the property 'CorrelatedEntities'
        /// </summary>
        [Fact]
        public void CorrelatedEntitiesTest()
        {
            // TODO unit test for the property 'CorrelatedEntities'
        }
    }
}
