/*
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenBankProject.Model;
using OpenBankProject.Client;
using System.Reflection;

namespace OpenBankProject.Test.Model
{
    /// <summary>
    ///  Class for testing GetMyApiCollectionEndpoints200ResponseApiCollectionEndpointsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetMyApiCollectionEndpoints200ResponseApiCollectionEndpointsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetMyApiCollectionEndpoints200ResponseApiCollectionEndpointsInner
        //private GetMyApiCollectionEndpoints200ResponseApiCollectionEndpointsInner instance;

        public GetMyApiCollectionEndpoints200ResponseApiCollectionEndpointsInnerTests()
        {
            // TODO uncomment below to create an instance of GetMyApiCollectionEndpoints200ResponseApiCollectionEndpointsInner
            //instance = new GetMyApiCollectionEndpoints200ResponseApiCollectionEndpointsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetMyApiCollectionEndpoints200ResponseApiCollectionEndpointsInner
        /// </summary>
        [Fact]
        public void GetMyApiCollectionEndpoints200ResponseApiCollectionEndpointsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetMyApiCollectionEndpoints200ResponseApiCollectionEndpointsInner
            //Assert.IsType<GetMyApiCollectionEndpoints200ResponseApiCollectionEndpointsInner>(instance);
        }

        /// <summary>
        /// Test the property 'OperationId'
        /// </summary>
        [Fact]
        public void OperationIdTest()
        {
            // TODO unit test for the property 'OperationId'
        }

        /// <summary>
        /// Test the property 'ApiCollectionId'
        /// </summary>
        [Fact]
        public void ApiCollectionIdTest()
        {
            // TODO unit test for the property 'ApiCollectionId'
        }

        /// <summary>
        /// Test the property 'ApiCollectionEndpointId'
        /// </summary>
        [Fact]
        public void ApiCollectionEndpointIdTest()
        {
            // TODO unit test for the property 'ApiCollectionEndpointId'
        }
    }
}
