/*
 * Open Bank Project API v6.0.0
 *
 * The Open Bank Project API v6.0.0 provides standardized banking APIs.  This specification was automatically generated from the OBP API codebase. Generated on: 2026-03-25T12:23:21.276369  For more information, visit: https://github.com/OpenBankProject/OBP-API
 *
 * The version of the OpenAPI document: 6.0.0
 * Contact: contact@tesobe.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenBankProject.Model;
using OpenBankProject.Client;
using System.Reflection;

namespace OpenBankProject.Test.Model
{
    /// <summary>
    ///  Class for testing ResetPasswordUrlAnonymousRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResetPasswordUrlAnonymousRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResetPasswordUrlAnonymousRequest
        //private ResetPasswordUrlAnonymousRequest instance;

        public ResetPasswordUrlAnonymousRequestTests()
        {
            // TODO uncomment below to create an instance of ResetPasswordUrlAnonymousRequest
            //instance = new ResetPasswordUrlAnonymousRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResetPasswordUrlAnonymousRequest
        /// </summary>
        [Fact]
        public void ResetPasswordUrlAnonymousRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResetPasswordUrlAnonymousRequest
            //Assert.IsType<ResetPasswordUrlAnonymousRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
    }
}
