/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openbankproject.models.CreateVRPConsentRequest200ResponsePayload
import com.openbankproject.models.CreateVRPConsentRequest200ResponsePayloadToAccount
import com.openbankproject.models.CreateVRPConsentRequestRequestFromAccount

class CreateVRPConsentRequest200ResponsePayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateVRPConsentRequest200ResponsePayload
        //val modelInstance = CreateVRPConsentRequest200ResponsePayload()

        // to test the property `fromAccount`
        should("test fromAccount") {
            // uncomment below to test the property
            //modelInstance.fromAccount shouldBe ("TODO")
        }

        // to test the property `toAccount`
        should("test toAccount") {
            // uncomment below to test the property
            //modelInstance.toAccount shouldBe ("TODO")
        }

        // to test the property `validFrom`
        should("test validFrom") {
            // uncomment below to test the property
            //modelInstance.validFrom shouldBe ("TODO")
        }

        // to test the property `timeToLive`
        should("test timeToLive") {
            // uncomment below to test the property
            //modelInstance.timeToLive shouldBe ("TODO")
        }

    }
}
