/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openbankproject.models.CreateTransactionRequestEthSendRawTransactionRequest

class CreateTransactionRequestEthSendRawTransactionRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateTransactionRequestEthSendRawTransactionRequest
        //val modelInstance = CreateTransactionRequestEthSendRawTransactionRequest()

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `params`
        should("test params") {
            // uncomment below to test the property
            //modelInstance.params shouldBe ("TODO")
        }

    }
}
