/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openbankproject.models.GetConsents200ResponseConsentsInnerJwtPayloadAccessTransactionsInner

class GetConsents200ResponseConsentsInnerJwtPayloadAccessTransactionsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetConsents200ResponseConsentsInnerJwtPayloadAccessTransactionsInner
        //val modelInstance = GetConsents200ResponseConsentsInnerJwtPayloadAccessTransactionsInner()

        // to test the property `msisdn`
        should("test msisdn") {
            // uncomment below to test the property
            //modelInstance.msisdn shouldBe ("TODO")
        }

        // to test the property `maskedPan`
        should("test maskedPan") {
            // uncomment below to test the property
            //modelInstance.maskedPan shouldBe ("TODO")
        }

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `pan`
        should("test pan") {
            // uncomment below to test the property
            //modelInstance.pan shouldBe ("TODO")
        }

        // to test the property `iban`
        should("test iban") {
            // uncomment below to test the property
            //modelInstance.iban shouldBe ("TODO")
        }

        // to test the property `bban`
        should("test bban") {
            // uncomment below to test the property
            //modelInstance.bban shouldBe ("TODO")
        }

    }
}
