/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openbankproject.models.GetConnectors200ResponseConnectorsInner

class GetConnectors200ResponseConnectorsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetConnectors200ResponseConnectorsInner
        //val modelInstance = GetConnectors200ResponseConnectorsInner()

        // to test the property `isAvailableInMethodRouting`
        should("test isAvailableInMethodRouting") {
            // uncomment below to test the property
            //modelInstance.isAvailableInMethodRouting shouldBe ("TODO")
        }

        // to test the property `connectorName`
        should("test connectorName") {
            // uncomment below to test the property
            //modelInstance.connectorName shouldBe ("TODO")
        }

    }
}
