/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openbankproject.models.GetConsentByConsentId200Response
import com.openbankproject.models.CreateConsentImplicitRequestEntitlementsInner

class GetConsentByConsentId200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetConsentByConsentId200Response
        //val modelInstance = GetConsentByConsentId200Response()

        // to test the property `scopes`
        should("test scopes") {
            // uncomment below to test the property
            //modelInstance.scopes shouldBe ("TODO")
        }

        // to test the property `jwt`
        should("test jwt") {
            // uncomment below to test the property
            //modelInstance.jwt shouldBe ("TODO")
        }

        // to test the property `consentRequestId`
        should("test consentRequestId") {
            // uncomment below to test the property
            //modelInstance.consentRequestId shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `consumerId`
        should("test consumerId") {
            // uncomment below to test the property
            //modelInstance.consumerId shouldBe ("TODO")
        }

        // to test the property `consentId`
        should("test consentId") {
            // uncomment below to test the property
            //modelInstance.consentId shouldBe ("TODO")
        }

    }
}
