/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openbankproject.models.GetFastFirehoseAccountsAtOneBank200ResponseAccountsInnerOwnersInner

class GetFastFirehoseAccountsAtOneBank200ResponseAccountsInnerOwnersInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFastFirehoseAccountsAtOneBank200ResponseAccountsInnerOwnersInner
        //val modelInstance = GetFastFirehoseAccountsAtOneBank200ResponseAccountsInnerOwnersInner()

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `userName`
        should("test userName") {
            // uncomment below to test the property
            //modelInstance.userName shouldBe ("TODO")
        }

        // to test the property `provider`
        should("test provider") {
            // uncomment below to test the property
            //modelInstance.provider shouldBe ("TODO")
        }

    }
}
