/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openbankproject.models.GetTransactionByIdForBankAccount200Response
import com.openbankproject.models.GetCoreTransactionsForBankAccount200ResponseTransactionsInnerDetails
import com.openbankproject.models.GetCoreTransactionsForBankAccount200ResponseTransactionsInnerThisAccount
import com.openbankproject.models.GetCoreTransactionsForBankAccount200ResponseTransactionsInnerTransactionAttributesInner
import com.openbankproject.models.GetTransactionByIdForBankAccount200ResponseMetadata
import com.openbankproject.models.GetTransactionByIdForBankAccount200ResponseOtherAccount

class GetTransactionByIdForBankAccount200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetTransactionByIdForBankAccount200Response
        //val modelInstance = GetTransactionByIdForBankAccount200Response()

        // to test the property `thisAccount`
        should("test thisAccount") {
            // uncomment below to test the property
            //modelInstance.thisAccount shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `details`
        should("test details") {
            // uncomment below to test the property
            //modelInstance.details shouldBe ("TODO")
        }

        // to test the property `metadata`
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `otherAccount`
        should("test otherAccount") {
            // uncomment below to test the property
            //modelInstance.otherAccount shouldBe ("TODO")
        }

        // to test the property `transactionAttributes`
        should("test transactionAttributes") {
            // uncomment below to test the property
            //modelInstance.transactionAttributes shouldBe ("TODO")
        }

    }
}
