/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.openbankproject.models.Root200Response
import com.openbankproject.models.Root200ResponseHostedAt
import com.openbankproject.models.Root200ResponseHostedBy

class Root200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Root200Response
        //val modelInstance = Root200Response()

        // to test the property `localIdentityProvider`
        should("test localIdentityProvider") {
            // uncomment below to test the property
            //modelInstance.localIdentityProvider shouldBe ("TODO")
        }

        // to test the property `resourceDocsRequiresRole`
        should("test resourceDocsRequiresRole") {
            // uncomment below to test the property
            //modelInstance.resourceDocsRequiresRole shouldBe ("TODO")
        }

        // to test the property `hostname`
        should("test hostname") {
            // uncomment below to test the property
            //modelInstance.hostname shouldBe ("TODO")
        }

        // to test the property `versionStatus`
        should("test versionStatus") {
            // uncomment below to test the property
            //modelInstance.versionStatus shouldBe ("TODO")
        }

        // to test the property `version`
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `hostedAt`
        should("test hostedAt") {
            // uncomment below to test the property
            //modelInstance.hostedAt shouldBe ("TODO")
        }

        // to test the property `connector`
        should("test connector") {
            // uncomment below to test the property
            //modelInstance.connector shouldBe ("TODO")
        }

        // to test the property `energySource`
        should("test energySource") {
            // uncomment below to test the property
            //modelInstance.energySource shouldBe ("TODO")
        }

        // to test the property `hostedBy`
        should("test hostedBy") {
            // uncomment below to test the property
            //modelInstance.hostedBy shouldBe ("TODO")
        }

        // to test the property `gitCommit`
        should("test gitCommit") {
            // uncomment below to test the property
            //modelInstance.gitCommit shouldBe ("TODO")
        }

    }
}
