/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param roleName 
 * @param bankId 
 * @param entitlementId 
 */


data class AddSystemViewPermission200Response (

    @Json(name = "role_name")
    val roleName: kotlin.String? = null,

    @Json(name = "bank_id")
    val bankId: kotlin.String? = null,

    @Json(name = "entitlement_id")
    val entitlementId: kotlin.String? = null

) {


}

