/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import com.openbankproject.models.CreateTransactionRequestCardanoRequestToAmount
import com.openbankproject.models.CreateTransactionRequestCardanoRequestToAssetsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param amount 
 * @param address 
 * @param assets 
 */


data class CreateTransactionRequestCardanoRequestTo (

    @Json(name = "amount")
    val amount: CreateTransactionRequestCardanoRequestToAmount? = null,

    @Json(name = "address")
    val address: kotlin.String? = null,

    @Json(name = "assets")
    val assets: kotlin.collections.List<CreateTransactionRequestCardanoRequestToAssetsInner>? = null

) {


}

