/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import com.openbankproject.models.GetCallsLimit200ResponseLimitsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param limits 
 */


data class GetCallsLimit200Response (

    @Json(name = "limits")
    val limits: kotlin.collections.List<GetCallsLimit200ResponseLimitsInner>? = null

) {


}

