/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import com.openbankproject.models.GetConsents200ResponseConsentsInnerJwtPayload

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createdByUserId 
 * @param jwtPayload 
 * @param provider 
 * @param consentReferenceId 
 * @param providerId 
 * @param apiVersion 
 * @param lastUsageDate 
 * @param note 
 * @param status 
 * @param consumerId 
 * @param apiStandard 
 * @param lastActionDate 
 */


data class GetConsents200ResponseConsentsInner (

    @Json(name = "created_by_user_id")
    val createdByUserId: kotlin.String? = null,

    @Json(name = "jwt_payload")
    val jwtPayload: GetConsents200ResponseConsentsInnerJwtPayload? = null,

    @Json(name = "provider")
    val provider: kotlin.String? = null,

    @Json(name = "consent_reference_id")
    val consentReferenceId: kotlin.String? = null,

    @Json(name = "provider_id")
    val providerId: kotlin.String? = null,

    @Json(name = "api_version")
    val apiVersion: kotlin.String? = null,

    @Json(name = "last_usage_date")
    val lastUsageDate: java.time.OffsetDateTime? = null,

    @Json(name = "note")
    val note: kotlin.String? = null,

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "consumer_id")
    val consumerId: kotlin.String? = null,

    @Json(name = "api_standard")
    val apiStandard: kotlin.String? = null,

    @Json(name = "last_action_date")
    val lastActionDate: java.time.OffsetDateTime? = null

) {


}

