/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import com.openbankproject.models.GetMyCustomersAtBank200ResponseCustomersInnerCreditLimit

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param newBalance 
 * @param description 
 * @param completed 
 * @param type 
 * @param `value` 
 * @param posted 
 */


data class GetCoreTransactionsForBankAccount200ResponseTransactionsInnerDetails (

    @Json(name = "new_balance")
    val newBalance: GetMyCustomersAtBank200ResponseCustomersInnerCreditLimit? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "completed")
    val completed: java.time.OffsetDateTime? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "value")
    val `value`: GetMyCustomersAtBank200ResponseCustomersInnerCreditLimit? = null,

    @Json(name = "posted")
    val posted: java.time.OffsetDateTime? = null

) {


}

