/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param panelId 
 * @param description 
 * @param panelName 
 * @param mandateId 
 * @param userIds 
 */


data class GetSignatoryPanel200Response (

    @Json(name = "panel_id")
    val panelId: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "panel_name")
    val panelName: kotlin.String? = null,

    @Json(name = "mandate_id")
    val mandateId: java.time.OffsetDateTime? = null,

    @Json(name = "user_ids")
    val userIds: kotlin.collections.List<kotlin.String>? = null

) {


}

