/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import com.openbankproject.models.GetCoreTransactionsForBankAccount200ResponseTransactionsInnerTransactionAttributesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param transactionAttributes 
 */


data class GetTransactionAttributes200Response (

    @Json(name = "transaction_attributes")
    val transactionAttributes: kotlin.collections.List<GetCoreTransactionsForBankAccount200ResponseTransactionsInnerTransactionAttributesInner>? = null

) {


}

