/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.openbankproject.models

import com.openbankproject.models.CreateTransactionRequestCounterparty200ResponseAttributesInner
import com.openbankproject.models.GetCheckbookOrders200ResponseAccountAccountRoutingsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param bankRoutings 
 * @param city 
 * @param postcode 
 * @param branch 
 * @param country 
 * @param attributes 
 * @param bank 
 * @param address 
 * @param phone 
 */


data class IbanChecker200ResponseDetails (

    @Json(name = "bank_routings")
    val bankRoutings: kotlin.collections.List<GetCheckbookOrders200ResponseAccountAccountRoutingsInner>? = null,

    @Json(name = "city")
    val city: kotlin.String? = null,

    @Json(name = "postcode")
    val postcode: kotlin.String? = null,

    @Json(name = "branch")
    val branch: kotlin.String? = null,

    @Json(name = "country")
    val country: kotlin.String? = null,

    @Json(name = "attributes")
    val attributes: kotlin.collections.List<CreateTransactionRequestCounterparty200ResponseAttributesInner>? = null,

    @Json(name = "bank")
    val bank: kotlin.String? = null,

    @Json(name = "address")
    val address: kotlin.String? = null,

    @Json(name = "phone")
    val phone: kotlin.String? = null

) {


}

